CREATE TABLE t_imput_casa (proyecto_id TEXT,informe_id TEXT,cliente TEXT,propietario TEXT,solicitante TEXT,ubicacion TEXT,tasacion_fecha TEXT,ubi_departamento TEXT,ubi_provincia TEXT,ubi_distrito TEXT,mapa_latitud TEXT,mapa_longitud TEXT,zonificacion TEXT,piso_cantidad TEXT,terreno_area TEXT,terreno_valorunitario TEXT,edificacion_area TEXT,valor_comercial TEXT,areas_complementarias TEXT,tipo_cambio TEXT,observacion TEXT,ruta_informe TEXT);
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11018","11017","CARLOS DANIEL ABARCA BARRIGA","CARLOS DANIEL ABARCA BARRIGA","BANCO DE CREDITO DEL PERU","CALLE LAURICOCHA MZ A´5 LOTE 8, URB PARTADA DEL SOL DE LA MOLINA, DISTRITO LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","17/10/2014","LIMA","LIMA","LA MOLINA","-12.1084984197610","-76.9401866537093","RDM","3","198.55","1400.00","416.96","418692.31","","2.9","El siguiente informe se realizó con las partidas del inmueble, entregadas por el banco Se realizo la tasación por exteriores por indicaciones del funcionaria Gavina Roman Godoy","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2013\\OCTUBRE\\TasBCP254-2013-11017 - ABARCA BARRIGA CARLOS DANIEL (11018)");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12842","12841","SONIA MERCEDES HUAMAN PALACIOS","JUAN ALBERTO SANCHEZ AZCUE Y SONIA MERCEDES HUAMAN PALACIOS","BANCO FINANCIERO DEL PERU","CALLE 5, MZ R LOTE 41, URBANIZACIÓN SANTA ANA,  DISTRITO DE LOS OLIVOS, PROVINCIA Y DEPARTAMENTO DE LIMA","31/07/2014","LIMA","LIMA","LOS OLIVOS","-11.9506837656079","-77.0770812374114","RDM","4","120.00","700.00","297.85","186460.40","","2.9","El siguiente informe se realizo según los documentos entregados por el Banco y el cliente: Partida Registral N°44238160, autovalúo 2014 y recibo de luz Las áreas construidas fueron obtenidas de la Partida Registral; ya que se encuentra toda la construcción declarada _x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo, el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco Financiero\\2014\\JUNIO\\TasFINANCIERO004-2014-12841 HUAMAN PALACIOS");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12840","12839","YANAC MIRANDA JESUS MACEDONIO","YANAC MIRANDA JESUS MACEDONIO","BANCO FINANCIERO DEL PERU","PROGRAMA CIUDAD MARISCAL CACERES, SECTOR I, 3RA Y 4TA ETAPA MZ K6 LOTE 25,  DISTRITO DE SAN JUAN DE LURIGANCHO, PROVINCIA Y DEPARTAMENTO DE LIMA","11/07/2014","LIMA","LIMA","SAN JUAN DE LURIGANCHO","-11.9608509918311","-76.9849795442580","RDM","2 + AZOTEA","90.00","250.00","180.00","116899.20","NO","2.9","Existe poca oferta de viviendas, la zona se encuentra en proceso de consolidación Las ofertas encontradas en la misma urbanización cuentan con similares características, por ello servirán como referencia para determinar el valor comercial del inmueble","Y:\\OPERACIONES\\Tasaciones\\Bco Financiero\\2014\\JUNIO\\TasFINANCIERO003-2014-12839 YANAC MIRANDA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12397","12396","RICARDO RONALD MAYORGA HUACAC ","RICARDO RONALD MAYORGA HUACAC Y AMALIA COSME ALVARADO DE MAYORGA","BANCO DE CREDITO DEL PERU","CASA DE ALTOS, AV BOLIVIA Nº 583, DISTRITO DE BREÑA, PROVINCIA Y DEPARTAMENTO DE LIMA ","07/05/2014","LIMA","LIMA","BREÑA","-12.0558781866525","-77.0386290889739","RDA","2","92.86","900.00","161.49","125359.54","","2.9","El siguiente informe se realizó según partida registral, la cual estaba incompleta, por indicación del funcionario Carlos Solano Ramos – Of Garantias_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\MAYO\\TasBCP107-2014-12396 - MAYORGA HUCAC RICARDO RONALD(F)");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12498","12497","GLOBAL TIRES PERU SAC","GLOBAL TIRES PERU SAC","BANCO CONTINENTAL","AVENIDA NICOLAS ARRIOLA Nº 2264,2266,2268, MZ B LOTE 5, URBANIZACION SAN LUIS, DISTRITO SAN LUIS, PROVINCIA Y DEPARTAMENTO DE LIMA","06/05/2014","LIMA","LIMA","SAN LUIS","-12.0710285023878","-77.0007562976836","I1","2","450.00","1500.00","522.48","775657.53","","2.8","El siguiente informe se realizó con documentos entregados por el banco como partida, autovalúo y tasación anterior _x000D_
La numeración del inmueble  que consigna la partida, no coincide con el autovalúo e inspección ocular, sin embargo la manzana y lote si, se está considerando la dirección según partida registral _x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MAYO\\TasBBVA122-2014-12497 GLOBAL TIRES");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12426","12425","BARBA BARAHONA JOSE LUIS","LEYTHON HOYOS MARIO ARMANDO","BANCO DE COMERCIO","AV INDUSTRIAL N° 268, ANTES PANAMERICANA NORTE Km 680, DISTRITO DE GUADALUPE, PROVINCIA DE PACASMAYO Y DEPARTAMENTO DE LA LIBERTAD","05/05/2014","LA LIBERTAD","PACASMAYO","GUADALUPE","","","RDM","3","185.64","110","281.85","74476.52","NO","2.6","El siguiente informe se realizó según partida registral y autovaluo por indicación de funcionaria Yessenia Gil Gallet – Administración de créditos_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_","Y:\\OPERACIONES\\Tasaciones\\Bco. Comercio\\2014\\MAYO\\TasCOMERCIO012-2014-12425- BARBA BARAHONA JOSE LUIS");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12468","12442","EMPRESA 4T CONTRATISTAS GENERALES SA","EMPRESA 4T CONTRATISTAS GENERALES SA","BANCO INTERBANK DEL PERU","URBANIZACIÓN POPULAR  ASOCIACION RURAL IND Y AGROP “LAS DELICIAS DE VILLA” MZ C13 LOTE 7, DISTRITO DE CHORRILLOS, PROVINCIA Y DEPARTAMENTO DE LIMA","05/05/2014","LIMA","LIMA","CHORRILLOS","-12.2010578425932","-76.9885629755019","RDB","1","1180.90","400.00","286.00","524857.60","","2.8","El informe ha sido realizado con los documentos entregados por el banco, tales como partida registral Nº P03220527 y autovalúo 2014 Se ha considerado parte de la edificación según autovaluo y el resto se ha estimado según inspección cular por no encontrarse inscrita en la partida _x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como patrimonio cultural de la humanidad_x000D_
_x000D_Asimismo, el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Interbank\\2014\\MAYO\\TasINTERBANK022-2014-12442 - 4T Contratistas Gnrls");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12469","12468","CONSTRUCCIONES Y PROYECTOS VIALES EIRL","MELITA HIDALGO SALAS","BANCO CONTINENTAL","CALLE Nº 146-148 (EX CALLE 8), URBANIZACION SANTA PATRICIA-SEGUNDA ETAPA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","29/04/2014","LIMA","LIMA","LA MOLINA","-12.0707422575828","-76.9436261359512","RDM","3","210.40","1000.00","350.96","352889.76","","2.8","Por indicaciones del Banco el siguiente informe se realizó por exteriores según las partidas registrales y tasación anterior Se está asumiendo el estado regular ya que no se ingreso al inmueble_x000D_
El inmueble no se encuentra ubicado dentro de una zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\ABRIL\\TasBBVA111-2014-12468 CONSTRUCCIONES Y PROYECTOS - SANTA PATRICIA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12470","12469","CONSTRUCCIONES Y PROYECTOS VIALES EIRL","HIDALGO SALAS MARIELA","BANCO CONTINENTAL","CALLE MARIA EGUSQUIZA DE GALVEZ Nº 157, URB PANDO, DISTRITO DE SAN MIGUEL, PROVINCIA Y DEPARTAMENTO DE LIMA","29/04/2014","LIMA","LIMA","SAN MIGUEL","-12.0838349570911","-77.0888239484786","RDM","3","160.00","1200.00","334.71","296027.87","","2.8","El presente informe se realizó con visita por exteriores, se contó con información proporcionada por el banco: Partida Registral N° 41030984 y hoja resumen de tasación anterior_x000D_
Se están tomando el área construida, antigüedad y estado de conservación según hoja resumen de tasación anterior ya que la partida registral no cuenta con declaratoria de fábrica Se recomienda actualizar dicho documento_x000D_
El inmueble no se encuentra ubicado dentro de una zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\ABRIL\\TasBBVA112-2014-12469 CONSTRUCCIONES Y PROYECTOS");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12458","12457","GYM MEGA FORCE EIRL","FERNANDO PABLO VEGA HUMALA","BANCO CONTINENTAL","AVENIDA UNIVERSITARIA Nº 6123, MZ H LOTE I, URBANIZACION DEL VILLA SOL, DISTRITO DE LOS OLIVOS, PROVINCIA Y DEPARTAMENTO DE LIMA","28/04/2014","LIMA","LIMA","LOS OLIVOS","-11.9631845715302","-77.0715988021850","CZ ","2","326.03","1850.00","131.50","638830.20","","2.8","El siguiente informe se realizó con documentos entregados por el banco como partida, autovalúo cabe indicar que la construcción se tomó del autovaluo ya que no se encuentra inscrita en la partida registral_x000D__x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\ABRIL\\TasBBVA108-2014-12457 GYM MEGA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12406","12405","CARPINTERIA FERRETERIA SANTA ANA EIRL","EDUARDO ALEJANDRO SALAS PALACIOS Y ERICKANIEVES SALAZAR TALAVERANO","BANCO CONTINENTAL","CALLE 04, MANZANA C, LOTE 06, URBANIZACION RESIDENCIAL RISSO, DISTRITO DE SANTA ANITA, PROVINCIA Y DEPARTAMENTO DE LIMA","23/04/2014","LIMA","LIMA","SANTA ANITA","-12.0355085465234","-76.9527393918990","RDM","4","160.00","600.00","434.00","233770.00","","2.8","El siguiente informe se realizó según documentos entregados como partida registral y autovaluo, se tomo el área construida según autovaluo ya que no se encuentra inscrita en partida_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\ABRIL\\TasBBVA103-2014-12405 CARPINTERIA FERRETERIA SANTA ANA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12161","12160","ABOGADOS – INGENIEROS SERVICE SRLTDA","MERCADO CARO LUIS AUGUSTO","BANCO DE CREDITO DEL PERU","AV 1ER AV LAS PALMERAS S/N MZ N LOTE 18 PARCELA SEMIRUSTICA PAPALEON XIII CHILCA - CAÑETE","21/04/2014","LIMA","LIMA","CAÑETE","-12.4717147177321","-76.7461502891540","RURAL","1","5053.00","65.00","120.00","382581.00","","2.9","El siguiente informe se realizó según los documentos brindados: autovalúo 2012, ficha registral (en letra corrida) pero estos documentos no se ajustaban a lo que se había observado en la inspección ocular, motivo por el cual se está procediendo a tasar tanto con documentación facilitada y por inspección ocular todo esto se realizó por indicación del funcionario del banco Marco Antonio Escudero Cabe recalcar que el inmueble cuenta con más frente, por lo tanto se está procediendo a tomar en cuenta el articulo IIC22 del Reglamento Nacional de Tasaciones del Perú_x000D_
_x000D_
A su vez cabe mencionar que el presente terreno / casa vivienda, no presenta dirección ni numeración, pero se constata que la zona corresponde a Papa León XIII, realizando la verificación por los linderos que cuenta en la partida registral_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\ABRIL\\TasBCP089-2014-12160  ABOGADOS-INGENIEROS SERVICE SRLTDA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12320","12319","FABIAN MESTRE JACQUELINE ANARELLA","FABIAN MESTRE JACQUELINE ANARELLA","BANCO INTERAMERICANO DE FINANZAS","Jirón VAN DE VELDE 183 DPTO 102 (MZ k8 LT9) - SAN BORJA - LIMA - LIMA","10/04/2014","LIMA","LIMA","SAN BORJA","-12093798241198702","-7698941348967280","RDB","4","30.92","2600","72835.97","197565.17","","2.6","El siguiente informe se realizó con la documentación entregada por el banco, por indicación de la funcionaria MAYRA COLLANTES, las cuales son Partidas Registrales y autovalúo _x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_","Y:\\OPERACIONES\\Tasaciones\\Bco. Bif\\2014\\ABRIL\\TasBIF020-2014-12319 - FABIAN MESTRE JACKELINE");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12304","12303","CORPORACION INMARCA SAC","BANCO DE CREDITO DEL PERU","CORPORACION INMARCA SAC","AV RAMÓN CASTILLA Nº1408-1412, URB LA CASTELLANA, DISTRITO DE SANTIAGO DE SURCO, PROVINCIA Y DEPARTAMENTO DE LIMA","08/04/2014","LIMA","LIMA","SANTIAGO DE SURCO","-12.1367111840407","-77.0045474142555","RDM","2 PISOS + AZOTEA","425.00","1800.00","343.18","852765.84","","2.8","El siguiente informe se realizó con la partida registral, Autovalúo y tasación anterior Se está tomando el área construida (34318) del PU 2013 ya que es la que más se aproxima de acuerdo a inspección se recomienda actualizar la Partida Registral con este dato","Y:\\OPERACIONES\\Tasaciones\\Clientes Particulares\\HERSIL\\2014\\ABRIL\\TasHERSIL015-2014-12303 - HERSIL CASA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12321","12320","INVERSIONES UNION PERU EIRL","MUÑOZ TAIPE ALEJANDRO","BANCO INTERBANK DEL PERU","URBANIZACIÓN POPULAR DE INTERÉS SOCIAL PROYECTO ESPECIAL CIUDAD PACHACÚTEC MZ J LOTE 10, GRUPO RESIDENCIAL 1, BARRIO XV, SECTOR G, DISTRITO DE VENTANILLA, PROVINCIA DEL CALLAO Y DEPARTAMENTO DE LIMA","07/04/2014","LIMA","CALLAO","VENTANILLA","-11.8417732979663","-77.1399522167205","RDM","1 PISO + AZOTEA","160.00","100.00","30.00","25975.00","","2.81","El informe ha sido realizado con los documentos entregados por el banco, tales como partida registral Nº P01029649 y autovalúo 2014_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como patrimonio cultural de la humanidad_x000D_
_x000D_
Asimismo, el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Interbank\\2014\\ABRIL\\TasINTERBANK020-2014-12320 - INVERSIONES UNIÓN PERÚ EIRL");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12314","12313","ALEJANDRO BUSTAMANTE","SILVANA ELENA GABRIELI ARIENZO","ALEJANDRO BUSTAMANTE","JR TRINIDAD Y MORAN Nº394 ESQUINA CON CALLE MARISCAL MILLER, DISTRITO DEL CERCADO DE LIMA, PROVINCIA Y DEPARTAMENTO DE LIMA","07/04/2014","LIMA","LIMA","CERCADO DE LIMA","-12.0896154963396","-77.0365959745406","RDB","","84.15","1500.00","146.34","222892.25","","2.8","El siguiente informe se realizó con las partidas registrales entregadas por Cliente Cabe recalcar que el área techada y la antigüedad se han tomado según inspección ocular ya que no se conto con autovaluo Así mismo según la partida registral el inmueble se ubica en el distrito del Cercado de Lima, sin embargo según inspección y plano de la zona este se ubica en el distrito de Lince, tal parece no se ha hecho la aclaración del mismo, se recomienda la actualización de dichos documentos Por tal motivo se está tomando el plano de zonificación del distrito de Lince debido a la ubicación del inmueble_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Clientes Particulares\\Otros Clientes\\2014\\ABRIL\\TasPart018-2014-12313 ALEJANDRO BUSTAMANTE");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12264","12263","ROCA SAC","JORGE MARTIN BUSHBY FAJARDO Y CLAUDIA LORENA CASTELLANOS ORJEDA","ROCA SAC","CALLE LAS FRAMBUESAS (EX LAS MORERAS) Nº 275 MZ B LOTE 16, ESQUINA CON CALLE LOS NARANJOS, URB LA FONTANA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","03/04/2014","LIMA","LIMA","LA MOLINA","-12.0750747367897","-76.9584578615188","RDB","2","363.58","1200.00","294.90","604978.80","","2.6","El presente informe ha sido elaborado de acuerdo a la documentación entregada por el Cliente Se recomienda actualizar la información declarada en Partida Registral y Autovalúo, pues físicamente el inmueble se ubica en la Calle Las Frambuesas Nº275 y no 205 como figura en los documentos antes mencionados Se procedió de esta manera según indicaciones del cliente","Y:\\OPERACIONES\\Tasaciones\\Clientes Particulares\\Otros Clientes\\2014\\ABRIL\\TasPart017-2014-12263 -ROCA SAC");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12227","12226","ALTAVISTA INVERSIONES GLOBALES SAC","JESUS REYES MUÑOZ LLANOS Y ANGELICA VICTORIA RAMOS SALAZAR","BANCO CONTINENTAL","AV VIA MALECON, MZ I, LOTE 26, UNIDAD INMOBILIARIA Nº 1, PRIMER PISO, URB ASOC DE VIVIENDA CHILLON, DISTRITO DE PUENTE PIEDRA, PROVINCIA Y DEPARTAMENTO DE LIMA","02/04/2014","LIMA","LIMA","PUENTE PIEDRA","-11.9205157160945","-77.0759547096252","RDM","2","56.57","280.00","140.37","81781.92","","2.8","El siguiente informe se realizó según documentos entregados como partida registral y tasación anterior Asimismo la antigüedad se consultó a la tasación anterior, ya que no se contó con autoavaluó_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\ABRIL\\TasBBVA081-2014-12226 ALTAVISTA INVERSIONES  UNID INM 1");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12283","12282","G & M METALES SAC","JUAN CARLOS LUGO SUAREZ","BANCO CONTINENTAL","JIRON LORETO Nº 732, DISTRITO DE BREÑA, PROVINCIA Y DEPARTAMENTO DE LIMA","31/03/2014","LIMA","LIMA","BREÑA","-12.0573484720264","-77.0482349755233","VT ","3 PISOS + AZOTEA","138.00","900.00","317.95","226738.88","","2.8","El siguiente informe se realizó por exteriores, por indicación del funcionario Rosly Medina, según documentos entregados por el banco: Tasación anterior del 04 de junio del 2013, realizada por la empresa Outsourcing SAC_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de una zona considerada como patrimonio cultural de la humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA079-2014-12282 G & M METALES");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12274","12273","CONFUMETAL","DENNIS WILLIAM DIAZ PAUCARIMA","BANCO CONTINENTAL","UNIDAD INMOBILIARIA Nº 102, JIRON VAN GENT Nº 109, URBANIZACION EL PACIFICO - II ETAPA, DISTRITO DE SAN MARTIN DE PORRES, PROVINCIA Y DEPARTAMENTO DE LIMA","28/03/2014","LIMA","LIMA","SAN MARTIN DE PORRES","-11.9979301185456","-77.0879370333618","RDM","2","129.32","650.00","129.31","127701.81","","2.8","Por indicaciones del Banco el siguiente informe se realizó por exteriores según las partidas registrales y tasación anterior Se está asumiendo el estado regular ya que no se ingreso al inmueble_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de una zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA075-2014-12273 COMFUMETAL");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12273","12272","SAMALLOA VELASQUEZ LUIS","ANA DE LOS MILAGROS SALVANY BARR","BANCO CONTINENTAL","CALLE LAS OROPENDOLAS Nº 200-210, URBANIZACION SAN JOAQUIN, DISTRITO DE BELLAVISTA, PROVINCIA Y CONSTITUCIONAL DEL CALLAO","28/03/2014","LIMA","CALLAO","BELLAVISTA","-12.0618390733931","-77.0953533412879","RDA","2 PISOS + AZOTEA","149.35","1000.00","179.94","201190.71","","2.8","El siguiente informe se realizo según los documentos entregados, partida registral Nº07013891 y tasación anterior realizada el 28 de diciembre del 2012, por la empresa MOSSEG SAC cabe recalcar que se tuvo ingreso al inmueble pero se está trabajando según la tasación anterior, ya que no se conto con las partidas completas Por indicaciones de la funcionaria Claudia Alencar of Colonial_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA076-2014-12272 SAMALLOA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12266","12265","MASTERWALL SA","LUIS ALBERTO BOCANEGRA RUIZ Y ELSA JESSICA AURORA CUADROS","BANCO CONTINENTAL","CALLE LIDO Nº 335-339, URBANIZACION SOL DE LA MOLINA I ETAPA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","26/03/2014","LIMA","LIMA","LA MOLINA","-12.0836177727689","-76.9096291424697","RDM","2","450.24","900.00","396.10","553515.84","","2.6","El siguiente informe se realizó por exteriores según las partidas registrales y tasación anterior Por indicaciones del Banco Se está asumiendo el estado regular ya que no se ingreso al inmueble_x000D__x000D_
El inmueble no se encuentra ubicado dentro de una zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA071-2014-12265  MASTER WALL");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12180","12179","CENTRO DE RESONANCIA MAGNETICA SAC","CENTRO DE RESONANCIA MAGNETICA SAC","CENTRO DE RESONANCIA MAGNETICA SAC","MZ K-3, LOTE 27, AV JAVIER PRADO N° 2620, URBANIZACIÓN SAN BORJA, TERCERA ETAPA, DISTRITO DE SAN BORJA, PROVINCIA Y DEPARTAMENTO DE LIMA","25/03/2014","LIMA","LIMA","SAN BORJA","-12.0876270985524","-76.9981876375144","CZ","3","420.00","2500.00","513.60","1191635.00","","2.81","Cabe indicar que las áreas construidas se basan del autoevaluó, ya que la partida no lo declara","Y:\\OPERACIONES\\Tasaciones\\Clientes Particulares\\CEREMA\\2014\\MARZO\\TasCEREMA0001-2014-12179 - CEREMA SAC (1)");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12226","12225","ALTAVISTA INVERSIONES GLOBALES SAC","OMAR JESUS MUÑOZ RAMOS","BANCO CONTINENTAL","AV VIA MALECON, MZ I, LOTE 26, UNIDAD INMOBILIARIA Nº 2 - SEGUNDO PISO, URBANIZACION ASOCIACION DE VIVIENDA CHILLON, DISTRITO DE PUENTE PIEDRA, PROVINCIA Y DEPARTAMENTO DE LIMA","24/03/2014","LIMA","LIMA","PUENTE PIEDRA","-11.9204593613493","-77.0759100081390","RDM","2","39.59","280.00","68.85","42677.02","","2.8","El siguiente informe se realizó según documentos entregados como partida registral y tasación anterior Cabe recalcar que el área de terreno se obtuvo según   reglamento nacional de tasaciones, ya que la tasación anterior declara un área que no corresponde al proporcional Asimismo la antigüedad se consultó a la tasación anterior, ya que no se contó con autovaluo _x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad _x000D_
_x000D_
El valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA065-2014-12225 - ALTAVISTA INVERSIONES");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12219","12218","FOKKER SRL","CESAR DE LA CRUZ GUTIERREZ, FIDEL DE LA CRUZ GUTIERREZ, LIDIA DE LA CRUZ GUTIERREZ, ESTHER HERRERA LUIS, TEOFILO DE LA CRUZ GUTIERREZ, ZOSIMO DE LA CRUZ GUTIERREZ Y PATRICIA ZENAIDA SALAZAR SUAREZ","BANCO INTERAMERICANO DE FINANZAS","MZ C-4, LOTE N° 7, URB SANTA AURELIA, DISTRITO DE SANTA ANITA, PROVINCIA Y DEPARTAMENTO DE LIMA","21/03/2014","LIMA","LIMA","SANTA ANITA","-12037341339631400","-7694998430006940","I1","5","453.18","900","415.69","1079834.4","","2.8","El siguiente informe se realizo según los documentos entregados por el banco como partida y autovalúo_x000D_","Y:\\OPERACIONES\\Tasaciones\\Bco. Bif\\2014\\MARZO\\TasBIF014-2014-12218  - FOKKER");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12207","12206","CONSORCIO ANGELITO SAC","HUATUCO RIVERA, ANGEL JULIAN","BANCO CONTINENTAL","AGRUPAMIENTO PACHACAMAC, MZ U, LOTE 19, TERCER SECTOR, ETAPA TERCERA, DISTRITO DE VILLA EL SALVADOR, PROVINCIA Y DEPARTAMENTO DE LIMA","21/03/2014","LIMA","LIMA","VILLA EL SALVADOR","-12.2240149083993","-76.9261408211654","RDM","4","100.00","250.00","240.00","94420.00","","2.8","El siguiente informe se realizó con documentos entregados por el banco: partida registral N° P03047767  y autoevalúo 2014, por indicaciones del funcionario Alejandro Revilla_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA063-2014-12206 - CONSORCIO ANGELITO");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12208","12207","ESTEBAN DEL AGUILA COLLANTES","ESTEBAN DEL AGUILA COLLANTES Y CLAUDIA DE LOS MILAGROS DE LA TORRE UGARTE MOSSELI","BANCO CONTINENTAL","JR DOMINGO DE LA PRESA Nº 368-362, URB VALLE HERMOSO DE MONTERRICO, DISTRITO DE SANTIAGO DE SURCO, PROVINCIA Y DEPARTAMENTO DE LIMA","20/03/2014","LIMA","LIMA","SANTIAGO DE SURCO","-12.1124811470945","-76.9748568874358","RDB","3","438.50","1600.00","597.21","958741.55","","2.8","El siguiente informe se realizó con la documentación entregada por el banco como partida registral, autovalúo y tasación anterior del 23 de junio del 2010, realizada por PROVALUA SAA_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como patrimonio cultural de la humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA061-2014-12207- ESTEBAN DEL AGUILA COLLANTES");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12196","12195","ZUZUNAGA INFANTES JULIO FELIPE","ZUZUNAGA INFANTES JULIO FELIPE Y MARIA TERESA ARIS TABOADA DE ZUZUNAGA","BANCO DE CREDITO DEL PERU","CALLE N (LOS GRANADOS) Nº 178 – 182, MANZANA B, LOTE Nº 11, URB VALLE HERMOSO DE MONTERRICO, DISTRITO DE SANTIAGO DE SURCO, PROVINCIA Y DEPARTAMENTO DE LIMA","19/03/2014","LIMA","LIMA","SANTIAGO DE SURCO","-12.1286366170902","-76.9700056673950","RDB","2 PISOS + AZOTEA","468.00","1300.00","299.74","760924.02","","2.9","El siguiente informe se realizó con la documentación entregada por el banco: partida registral N°44500086 y tasación anterior del Ing Luis E Zúñiga Remy con fecha 13 de marzo del 2013 Se realizó la tasación por exteriores por indicaciones del funcionaria Gavina Román Godoy_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como patrimonio cultural de la humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\MARZO\\TasBCP071-2014-12195 - ZUZUNAGA INFANTES JULIO FELIPE");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12194","12193","AQUARIUM VIDRIOS Y ALUMINIOS EIRL","OSWALDO ORDOÑEZ QUIROS","BANCO INTERBANK DEL PERU","JIRON MANUEL IRRIBARREN N° 1049 - DPTO 01, DISTRITO DE SURQUILLO, PROVINCIA Y DEPARTAMENTO DE LIMA","19/03/2014","LIMA","LIMA","SURQUILLO","-12.1108565750981","-77.0225876929229","RDM","2","44.00","1300.00","90.99","77081.32","","2.8","El siguiente informe se realizó según los documentos entregados tales como Partida Registral y Autoevalúo 2014 _x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Interbank\\2014\\MARZO\\TasINTERBANK016-2014-12193 - AQUARIUM VIDRIOS Y ALUMINIOS EIRL");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12192","12191","SHOCKING SAC","ELSA ADELAIDA ORDIALES VERANO DE YALAN, JORQUE LUIS YALAN ORDIALES, JESSIE VERONICA YALAN ORDIALES, ELSA LUZ YALAN ORDIALES Y JUAN PABLO YALAN ORDIALES","BANCO INTERBANK DEL PERU","FINCA DE DOS PLANTAS AVENIDA DANIEL HERNANDEZ PARTE DEL LOTE 68 MANZANA 6 URBANIZACIÓN EL CARMEN, DISTRITO DE PUEBLO LIBRE, PROVINCIA Y DEPARTAMENTO DE LIMA","18/03/2014","LIMA","LIMA","PUEBLO LIBRE","-12.0747893508500","-77.0686143996185","RDM","3","165.40","1400.00","278.10","330285.50","","2.8","El informe ha sido realizado con los documentos entregados por el banco, tales como partida registral Nº40748946 y autovalúo 2014_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como patrimonio cultural de la humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
Se observa hacia el lado derecho del inmueble un pasaje enrejado que según autovalúo es área común de la cual el 4236% le pertenece El segundo piso del inmueble abarca una parte de los aires de este pasaje, el propietario indica que así se levantó la construcción, debido a que todas las propiedades que comparten la zona común eran inicialmente de un solo propietario Se recomienda corroborar información sobre la propiedad de los aires_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Interbank\\2014\\MARZO\\TasINTERBANK015-2014-12191 - SHOCKING");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12187","12186","EVELYN CECILIA SOLANO ALIAGA","EVELYN CECILIA SOLANO ALIAGA","BANCO INTERAMERICANO DE FINANZAS","MANZANA 3-T SUB LOTE 4-B, URBANIZACIÓN PARCELACIÓN SEMIRÚSTICA EL SOL DE LA MOLINA III ETAPA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","17/03/2014","LIMA","LIMA","LA MOLINA","-12085737052224800","-7689908031586910","RDB","2 PISOS + AZOTEA","500","900","550.68","692327.23","","2.6","El siguiente informe se realizó con la documentación entregada por el banco: partida registral N°12848404 y autovalúo 2013_x000D_
_x000D_Cabe recalcar que se está asumiendo las áreas construidas del 1er y 2do piso según la partida y el  área de la azotea según autovalúo, ya que es lo que más se asemeja a lo inspeccionado por el Perito _x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_","Y:\\OPERACIONES\\Tasaciones\\Bco. Bif\\2014\\MARZO\\TasBIF012-2014-12186 - EVELYN SOLANO ALIAGA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12164","12163","SANDRA LILIANA CASTAÑEDA VILLALOBOS","ALFONSO ENRIQUE CESPEDES PERLA Y NANCY JANETT CASTAÑEDA FARRO","SANDRA LILIANA CASTAÑEDA VILLALOBOS","     PASAJE SAN JOSE Nº 166 Y 168,  DISTRITO DE MAGDALENA DEL MAR, PROVINCIA Y DEPARTAMENTO DE LIMA","10/03/2014","LIMA","LIMA","MAGDALENA DEL MAR","-12.0926469765118","-77.0715245963996","RDM","2","124.80","1200.00","242.60","206916.56","","2.8","El siguiente informe se realizó por exteriores según las partidas registrales y autovalúo Por indicaciones del cliente Se está asumiendo el estado regular ya que no se ingreso al inmueble_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Clientes Particulares\\Otros Clientes\\2014\\MARZO\\TasPART016-2014-12163 SANDRA CASTAÑEDA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12108","12107","ARIAS DELGADO JOSE ANTONIO","JOSE ANTONIO ARIAS DELGADO Y MARIA MILAGROS VILLARAN ZEGARRA","BANCO DE CREDITO DEL PERU","SUB LOTE B1 CON FRENTE AL JR LA CORUÑA (N° 355), HABILITACIÓN SEMI URBANA LA ESTANCIA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","07/03/2014","LIMA","LIMA","LA MOLINA","-12.0873333515503","-76.9358396889633","RDB","2","960.08","1200.00","642.94","1458487.60","","2.9","El siguiente informe se realizó por exteriores y se contó con la documentación entregada por el banco: Partida Electrónica Nº 11665396 y tasación anterior, por indicación de la funcionaria Ericka Obregon_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\MARZO\\TasBCP066-2014-12107 - ARIAS DELGADO JOSE ANTONIO  LA CORUNA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12115","12114","CORPORACION ARDYVAN  SAC","CARLOS DANIEL HERRERA CRUZ","BANCO CONTINENTAL","PASAJE SAN LORENZO Nº 264, DISTRITO DE LA VICTORIA, PROVINCIA Y DEPARTAMENTO DE LIMA","06/03/2014","LIMA","LIMA","LA VICTORIA","-12.0662862518492","-77.0252287727355","VT ","3","72.02","750.00","187.88","82142.22","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral Nº43277693 y Autovaluo2014 ","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA038-2014-12114  CORPORARION ARDYVAN 264");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12116","12115","CORPORATION ARDYVAN SAC","CARLOS DANIEL HERRERA CRUZ","BANCO CONTINENTAL","PASAJE SAN LORENZO Nº 268, URBANIZACION HUERTA MENDOZA, DISTRITO DE LA VICTORIA, PROVINCIA Y DEPARTAMENTO DE LIMA","06/03/2014","LIMA","LIMA","LA VICTORIA","-12.0665590384469","-77.0251643997191","VT ","3","138.00","750.00","360.00","124686.80","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral Nº07030451 y Autovaluo2014","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA039-2014-12115 CORPORATION ARDYVAN  268");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12157","12156","CORPORATION ARDYVAN SAC","JOSE ABRAHAM HERRERA CRUZ","BANCO CONTINENTAL","PASAJE SAN LORENZO Nº 272, DISTRITO DE LA VICTORIA, PROVINCIA Y DEPARTAMENTO DE LIMA","06/03/2014","LIMA","LIMA","LA VICTORIA","-12.0658875632454","-77.0252716880797","VT ","3 PISOS + AZOTEA","72.02","750.00","187.88","82142.22","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral Nº43267426 y Autovaluo2014 _x000D__x000D__x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA043-2014-12156 BBVA CORPORACION ARDYVAN 272");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12145","12144","CORPORAION YSIQUE SAC","LUIS JORGE MARROQUIN REDHEAD","BANCO CONTINENTAL","CALLE GENERAL VARELA Nº 1050-1038, DISTRITO DE BREÑA, PROVINCIA Y DEPARTAMENTO DE LIMA","06/03/2014","LIMA","LIMA","BREÑA","-12.0592216817176","-77.0459086042403","CZ ","2 PISOS + AZOTEA","152.10","1300.00","261.00","230616.00","","2.8","El siguiente informe se realizó con documentos entregados por el banco: partida registral N° 49002192  y autovalúo 2014, por indicaciones del funcionario Paolo Guevara_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Continental\\2014\\MARZO\\TasBBVA044-2014-12144 CORPORACION YSIQUE CASA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12120","12119","ELSA CANDELA CASAS","CASANOVA CASTILLO ANDRES PEDRO ALFONSO Y CANDELA CASAS ELSA","BANCO CONTINENTAL","PUEBLO JOVEN SAN FRANCISCO DE LA TABLADA DE LURIN, MZ 4E, SUB LOTE 30-A, SECTOR PRIMERO, DISTRITO DE VILLA MARIA DEL TRIUNFO, PROVINCIA Y DEPARTAMENTO DE LIMA","28/02/2014","LIMA","LIMA","VILLA MARIA DEL TRIUNFO","-12199252462375200","-7692713361376800","RDM","3","6958.00","250.00","20258.00","72000.00","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral NºP03284154 y Autoevalúo2013","Y:\\OPERACIONES\\Tasaciones\\Bco Continental\\2014\\FEBRERO\\TasBBVA036-2014-12119 ELSA CANDELA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12124","12123","PERCY NICHO RAMIREZ","PERCY NICHO RAMIREZ Y SADITH MARIAM MASGO CUBAS","BANCO DE CREDITO DEL PERU","AV CAMINOS DEL INCA Nº 1661 - 1665, URBANIZACIÓN LAS GARDENIAS, DISTRITO DE SANTIAGO DE SURCO, PROVINCIA Y DEPARTAMENTO DE LIMA","27/02/2014","LIMA","LIMA","SANTIAGO DE SURCO","-12.1265618337005","-76.9819003683089","RDM","3","294.52","2000.00","122.75","626601.50","","2.9","El siguiente informe se realizó con las partidas del inmueble entregadas por el banco Se realizó la tasación por exteriores por indicaciones del funcionaria Diana Diego Torres_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
Para la presente tasación no se está considerando el tercer piso debido a que no se encuentra declarada y no se puede estimar el área_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP062-2014-12123 - NICHO RAMIREZ PERCY");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12097","12096","GOALSA DISTRIBUIDORES SAC","GOMEZ SALAVERRY YVAN AMERICO Y ALVAREZ RODRIGUEZ ERIKA HAYDE","BANCO DE CREDITO DEL PERU","PUEBLO JOVEN PROYECTOS ESPECIALES MZ 57 LOTE 14, DISTRITO DE SAN JUAN DE LURIGANCHO, PROVINCIA Y DEPARTAMENTO DE LIMA ","25/02/2014","LIMA","LIMA","SAN JUAN DE LURIGANCHO","-11.9702586594656","-76.9983423095702","RDM","3","90.00","380.00","255.00","105300.00","","2.9","El siguiente informe se realizó con la documentación entregada por el banco, por indicación de la funcionaria Manuelita Niño Pajuelo_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP053-2014-12096 - GOALSA DISTRIBUIDORES S.A.C");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12095","12094","D&D CONTRATISTAS GENERALES EIRL","D & D CONTRATISTAS GENERALES EIRL","BANCO DE CREDITO DEL PERU","JIRON AYACUCHO N°564, URBANIZACIÓN DEL FUNDO ARBEA, DISTRITO DE MAGDALENA DEL MAR, PROVINCIA Y DEPARTAMENTO DE LIMA","25/02/2014","LIMA","LIMA","MAGDALENA DEL MAR","-12.0872760190925","-77.0690507036208","RDA","2","130.56","1200.00","151.67","194286.16","","2.9","El siguiente informe se realizó con la documentación entregada por el banco: Partida Registral N° 07005866 y Autovalúo 2012, por indicación de la funcionaria Manuelita Niño Pajuelo_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP056-2014-12094 - D & D CONTRATISTAS GENERALES E.I.R.L");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12079","12078","AVILA INGA RUBEN FELIX","AVILA INGA RUBEN FELIX","BANCO DE CREDITO DEL PERU","CALLE LOS ALAMOS MZ C – MA LOTE 4 Y 5, URBANIZACION CLUB RESIDENCIAL LOS GIRASOLES DE HUAMPANI, DISTRITO DE CHACLACAYO, PROVINCIA Y DEPARTAMENTO DE LIMA","21/02/2014","LIMA","LIMA","CHACLACAYO","-11.9716300734121","-76.7854768377303","ZHR","","400.00","350.00","380.37","241939.16","","2.9","El presente informe se a realizado con la documentación proporcionada por el Banco, Tasación anterior, como único documento sustentatorio, cabe mencionar que no se tuvo acceso a interiores de la Urb Club Residencial Los Girasoles de Huampani ya que guardianía no permitió el ingreso sin autorización del propietario, se ha realizado una tasación referencial asumiendo las características registradas en tasación anterior Todo lo antes mencionado ha sido autorizado por la Srta Ericka Obregón, funcionaria del BANCO DE CREDITO DEL PERU Se recomienda una inspección por interiores a fin de determinar el real estado del inmueble_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP050-2014-12078 - AVILA INGA RUBEN FELIX");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12000","11999","CARLOS ANDERSON TORRE COPA","CARLOS ANDERSON TORRE COPA Y GRACIELA ILAITA AQUISE","BANCO DE CREDITO DEL PERU","JIRON LAS GOLONDRINAS N° 237, MZ D-UNO LOTE 5, URBANIZACION SANTA ANITA, DISTRITO DE SANTA ANITA, PROVINCIA Y DEPARTAMENTO DE LIMA","20/02/2014","LIMA","LIMA","SANTA ANITA","-12.0521263228268","-76.9638276439666","RDM","2","203.00","800.00","292.34","233497.09","","2.9","El siguiente informe se realizó según los documentos entregados Se están considerando las áreas edificadas del autovalúo por ser el único documento que registra dicha área, en inspección se pudo observar que existe aparentemente un bloque posterior de tres niveles que no se encuentra registrado en ningún documento, por las características del inmueble no se puede asumir dicha área edificada Se recomienda actualizar los documentos o proporcionar plano de la edificación_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP049-2014-11999 TORRE COPA CARLOS ANDERSON");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12063","12062","ZAMAC DERIVADOS DEL PERU SAC – ZAYDER PERU SAC","GONZALES DELACRUZ GILBER JULIO","BANCO DE CREDITO DEL PERU","ASOCIACIÓN DE VIVIENDA RESIDENCIAL LOS SAUCES MZ M LT 6, DISTRITO DE PUENTE PIEDRA, PROVINCIA Y DEPARTAMENTO DE LIMA","19/02/2014","LIMA","LIMA","PUENTE PIEDRA","-11.9099209380449","-77.0727736097335","ZHR","5","179.60","350.00","693.48","293407.82","","2.9","El siguiente informe se realizó con la documentación entregada por el banco: Partida Registral N° P01243631 y Autovalúo del 2013, por indicación de la funcionaria Gavina Román Godoy_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP044-2014-12062 - ZAMAC DERIVADOS DEL PERU S.A.C");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12064","12063","IMPORTADORA MEGA EIRL","JAVIER OSCAR ALZAMORA FUERTES","BANCO INTERBANK DEL PERU","CALLE 14 MANZANA L LOTE 17, URBANIZACION SESQUICENTENARIO, DISTRITO DEL CALLAO Y PROVINCIA CONSTITUCIONAL DEL CALLAO","19/02/2014","LIMA","CALLAO","CALLAO","-12.0097994660519","-77.0969134908675","RDM","2","158.00","450.00","255.30","152796.00","","2.8","El siguiente informe se realizó con la documentación entregada por el banco como partida registral y autovaluo _x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan _x000D_
Se están considerando las áreas construidas de partida registral, por ultimo se recomienda actualizar el autovaluo_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Interbank\\2014\\FEBRERO\\TasINTERBANK 011-2014-12063 - IMPORTADORA MEGA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12060","12059","GALING EIRL","CARLOS NOE GALVEZ GONZALES Y VILMA SUSANA PAREDES BENITES","BANCO CONTINENTAL","AV ALFREDO MENDIOLA Nª 6059, URB VILLA SOL, PRIMERA ETAPA, DISTRITO DE LOS OLIVOS, PROVINCIA Y DEPARTAMENTO DE LIMA","18/02/2014","LIMA","LIMA","LOS OLIVOS","-11960834395475798","-7706962741619410","RDM","4","150.00","900.00","39248.00","290000.00","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral Nº43777750 y Autoevalúo2014 ","Y:\\OPERACIONES\\Tasaciones\\Bco Continental\\2014\\FEBRERO\\TasBBVA030-2014-12059 GAL ING EIRL  - VIVIENDA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12050","12049","JOSE LUIS DIAZ CONDOR","JOSE LUIS DIAZ CONDOR Y PATRICIA DEL ROSARIO MANRIQUE MUÑOZ","BANCO DE CREDITO DEL PERU","CALLE EDUARDO DEL CASTILLO N° 2315-2321 URBANIZACIÓN VIVIENDA, DISTRITO CERCADO DE LIMA, PROVINCIA Y DEPARTAMENTO DE LIMA","18/02/2014","LIMA","LIMA","CERCADO DE LIMA","-12.0621463314015","-77.0635253530501","RDM","2","153.00","900.00","107.10","169401.60","","2.9","El siguiente informe se realizó con la documentación entregada por el cliente: Partida Electrónica N°49068261, por indicación de la funcionaria Marisol Román Godoy_x000D_
_x000D_El área construida se ha considerado según inspección ocular, ya que no se contó con ningún documento registral que lo respalde_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP036-2014-12049 - DIAZ CONDOR JOSE LUIS - G193-69217");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11996","11995","CONVERTIDORA GUIJESA SAC ","CARBAJAL ESPINOZA CARMEN, CESPEDES CARBAJAL JENNY JUANA, CESPEDES CARBAJAL MARIA DEL CARMEN Y CESPEDES CARBAJAL JIMMY GIANCARLO","BANCO DE CREDITO DEL PERU","AV BENJAMÍN FRANKLIN N°556, MZ Z LT 11, AAHH MARGINAL ASOC PRO-VIVIENDA SICUANI, DISTRITO DE ATE, PROVINCIA Y DEPARTAMENTO DE LIMA","18/02/2014","LIMA","LIMA","ATE VITARTE","-12.0664480003197","-76.9759834152221","CV","3 PISOS + AZOTEA","120.00","700.00","246.20","141387.30","","2.9","El siguiente informe se realizó con la documentación entregada por el banco: Partida Registral N° P02010340 y Autovalúo del 2013, por indicación de la funcionaria Gavina Román Godoy_x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP043-2014-11995 - CONVERTIDORA GUIJESA S.A.C");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12052","12051","SANTIAGO FRANCISCO GERBOLINI PESHEIRA","ARMANDO ENRIQUE BACA DAUBE Y ANA MARIA CECILIA CASTRO ALZAMORA","BANCO DE CREDITO DEL PERU","CALLE MARIANO ODICIO Nº445, BAJOS, DISTRITO DE MIRAFLORES, PROVINCIA Y DEPARTAMENTO DE LIMA","17/02/2014","LIMA","LIMA","MIRAFLORES","-12.1240399874093","-77.0233002644538","RDM","3","96.68","2000.00","207.34","357378.87","","2.9","El siguiente informe se realizó con las partidas del departamento, entregadas por el banco Se realizo la tasación por exteriores por indicaciones del funcionaria Gavina Román Godoy_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP040-2014-12051 GERBOLINI PESCHIERA - G193-39498");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11940","11939","INMOBILIARIA AYAMARKA SAC","MARIA VANESSA OTERO HERNANDO, PAOLO OLCESE UGARTE Y UMBERTO OLCESE UGARTE","BANCO DE CREDITO DEL PERU","CALLE MONTEBLANCO Nº102, 104,  106 Y CALLE SELVA NEGRA, SUB LOTE 10, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","14/02/2014","LIMA","LIMA","LA MOLINA","-12.0755372346556","-76.9305682521819","RDB","3","773.95","750.00","441.07","804746.58","","2.9","El siguiente informe se realizó con los documentos proporcionados por el Banco; adicional a ello es importante mencionar que durante la inspección ocular físicamente el inmueble se encuentra en esquina de una calle sin salida y a partir de esa calle comienza la numeración de la calle Monte Blanco con el Nº305, ante ello no se puede dar fe de que los documentos entregados pertenezcan al inmueble inspeccionado, por lo cual se recomienda regularizar las partidas Asimismo se contó con la autorización de la funcionaria del Banco para proceder con el presente informe_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP033-2014-11939 - INMOBILIARIA AYAMARKA S.A.C");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12038","12037","CORPORACION TEXTIL T&C SAC","BANCO DE CREDITO DEL PERU","BANCO DE CREDITO DEL PERU","VIVIENDA 102 – PRIMER PISO, JIRON SAMOA Nº291-295, URBANIZACION EL SOL DE LA MOLINA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","13/02/2014","LIMA","LIMA","LA MOLINA","-12.0844093447550","-76.8979257684707","RDB","1","159.67","1000.00","142.92","237740.05","","2.9","El siguiente informe se realizó con la documentación entregada por el banco, por indicación de la funcionaria Gavina Román Godoy _x000D_
_x000D_El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP031-2014-12037 - CORPORACION TEXTIL T & C SAC");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11961","11960","SIHUAS SERVICIOS GENERALES SAC","MOSCOL HERRERA MARIA MAGDALENA ","BANCO INTERAMERICANO DE FINANZAS","ASENTAMIENTO HUMANO, URB PERU, JR LIBERTAD N° 3800 Y JR HUANCAYO N° 190-186, UNIDAD INMOBILIARIA N° 1 – ZONA 7, 1° Y 2° PISO, DISTRITO DE SAN MARTIN DE PORRES, PROVINCIA Y DEPARTAMENTO DE LIMA","12/02/2014","LIMA","LIMA","SAN MARTIN DE PORRES","-12026535250212900","-7708817588186030","RDM","3","86.27","850","217.3","147673.26","","2.6","El informe se ha elaborado con la documentación proporcionada por el Banco: Partida Electrónica y Autoevalúo Así mismo la antigüedad según autovaluo es de 02 años, sin embargo durante la inspección se pudo apreciar que el inmueble tiene mas años de antigüedad por lo cual  se considera en estado regular y se toman  los 02 años de antigüedad según autovaluo_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Bif\\2014\\FEBRERO\\TasBIF007-2014-11960 - SIHUAS SERVICIOS GENERALES");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12025","12024","DISTRIBUIDORA EYSKENS EIRL","SANCHEZ PICON FREDY ELMER","BANCO CONTINENTAL","PLAN INTEGRAL PALMAS DE SAN JUAN, MZ F, LOTE II, PUEBLO JOVEN JOSE CARLOS MARIATEGUI, DISTRITO DE SAN JUAN DE MIRAFLORES, PROVINCIA Y DEPARTAMENTO DE LIMA","11/02/2014","LIMA","LIMA","SAN JUAN DE MIRAFLORES","-121895159831326","-769621172848999","RDM","3","140.00","220.00","332.00","140000.00","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral y Autovalúo 2,013 Cabe indicar que el área construida no se encuentra declarada en su totalidad, por lo que solo se constató en autoevaluó primer y segundo piso del bloque I – parte delantera, asimismo, la ubicación se constató por el numero de medidor, ya que el inmueble no contaba con alguna forma de identificación","Y:\\OPERACIONES\\Tasaciones\\Bco Continental\\2014\\FEBRERO\\TasBBVA023-2014-12024 DISTRIBUIDORA EYSKENS");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("12007","12006","MARIO JESUS IGREDA COZ","MARIO JESUS IGREDA COZ","BANCO DE CREDITO DEL PERU","JR PROLONGACIÓN AYACUCHO Nº424 (MZ B LOTE 5) URB SAN MIGUELITO, DISTRITO DE SAN MIGUEL, PROVINCIA Y DEPARTAMENTO DE LIMA","07/02/2014","LIMA","LIMA","SAN MIGUEL","-12.0845282437483","-77.0767486434936","RDM","3","142.50","800.00","301.05","211540.20","","2.9","El siguiente informe se realizó por exteriores y no se contaron partidas solo se conto con la Tasación Anterior por indicación de la funcionaria Gavina Roman Godoy, dicha tasación no cuenta con el dato de Propietario del inmueble_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\FEBRERO\\TasBCP029-2014-12006 - IGREDA COZ MARIO JESUS  N° Garantía G193-38627");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11984","11983","IGNACIO MANUEL ROUILLON GARCIA ","IGNACIO MANUEL ROUILLON GARCIA Y MONICA PATRICIA PAREDES DEMARINI","BANCO DE CREDITO DEL PERU","AV LAGUNA GRANDE N° 698 – URB CLUB CAMPESTRE LAS LAGUNAS DE LA MOLINA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","31/01/2014","LIMA","LIMA","LA MOLINA","-120820345025087","-769160530272781","RDB","4","1367.00","1100.00","513.00","16886308.00","","2.9","El siguiente informe se realizó con la documentación entregada por el banco, por indicación de la funcionaria Gavina Roman Godoy Según indicación del cliente, este mismo hace uso del inmueble_x000D_
_x000D_
Se están considerando las áreas de Autovalúo, ya que en la Partida Registral se cuenta con la declaratoria de fabrica, sin embargo en ella no se registra las áreas edificadas Se recomienda actualizar la Partida_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco Credito\\2014\\ENERO\\TasBCP017-2014-11983 - ROUILLON GARCIA IGNACIO MANUEL");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11976","11975","CORPORACION EDITORA COREDISE SAC","CORPORACION EDITORA COREDISE SAC","BANCO INTERAMERICANO DE FINANZAS","DEPARTAMENTO N° 2, CALLE B, LOTE 23, MZ I, URB COVIMA, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","29/01/2014","LIMA","LIMA","LA MOLINA","-12.0611810693824","-76.9448644262313","RDM","2","57.53","1400.00","144.75","165865.51","","2.6","El informe se ha elaborado con la documentación proporcionada por el Banco: Partida Electrónica N° 11105538 y Autovalúo 2014","Y:\\OPERACIONES\\Tasaciones\\Bco. Bif\\2014\\ENERO\\TasBIF005-2014-11975 - COREDISE SAC - departamento duplex");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11929","11928","CHE MAQUINARIAS & CONSTRUCIONES SAC","CESAR FERNANDO HERNANDEZ ESPINOZA Y NANCY PALIZA HUERTA DE HERNANDEZ","BANCO INTERBANK DEL PERU","CALLE LAS GRULLAS N° 191, URB SANTA CECILIA, DISTRITO BELLAVISTA, PROVINCIA CALLAO, DEPARTAMENTO DE LIMA","16/01/2014","LIMA","CALLAO","BELLAVISTA","-12.0595548048613","-77.0950788599013","RDB","3","156.00","900.00","201.11","206739.59","","2.8","El informe ha sido realizado con los documentos entregados por el banco tales como Partida Registral Nº 70094799 y Autovalúo 2013","Y:\\OPERACIONES\\Tasaciones\\Bco. Interbank\\2014\\ENERO\\TasINTERBANK 002-2014-11928 - CHE MAQUINARIAS & CONSTRUCCION SAC - CASA");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11924","11923","INVERSIONES ALCAVEL SAC","GIANCARLO ALDO SATTUI CASTAÑEDA, LIBIA MARCELA CASTAÑEDA DE SATTUI , LUIS EDUARDO SATTUI  CASTAÑEDA, MARCELA CASTAÑEDA QUERZOLA  VIUDA DE SATTUI , MARCELA RUTH SATTUI  CASTAÑEDA, PATRICIA ISABEL SATTUI CASTAÑEDA, RAUL SATTUI  AGUSTI","BANCO CONTINENTAL","AV ERNESTO DIEZ CANSECO Nª 650-658, DISTRITO DE MIRAFLORES, PROVINCIA Y DEPARTAMENTO DE LIMA","15/01/2014","LIMA","LIMA","MIRAFLORES","-121216777352907","-770234164897263","RDB","3","4605.00","2500.00","515.00","1054000.00","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral Nº 46676327 y Autovalúo 2013 _x000D_
_x000D_
No se ha encontrado mayor detalle sobre la declaratoria de fábrica debido a la falta de legibilidad de la Partida Registral, no obstante la edificación se ha considerado como valores inscritos en los RRPP teniendo en cuenta que en la Partida el inmueble se describe como una Casa Residencial de dos Plantas, se recomienda actualizar la Partida Registral_x000D_","Y:\\OPERACIONES\\Tasaciones\\Bco Continental\\2014\\ENERO\\TasBBVA008-2014-11923 INVERSIONES ALCAVEL");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11866","11865","DAVID RUIZ","ASOCIACIÓN CIVIL PLAYA MISTERIO","DAVID RUIZ","MZ D  LOTE N° 6, URBANIZACIÓN HABILIATACIÓN VACACIONAL PLAYA MISTERIO, DISTRITO DE ASIA, PROVINCIA CAÑETE Y DEPARTAMENTO DE LIMA","09/01/2014","LIMA","CAÑETE","ASIA","-12.9064146087817","-76.5104055744170","RDM","5","359.00","1000.00","461.51","630471.72","","2.8","El siguiente informe se trabajó con los documentos proporcionados por el Cliente: Partida Registral, Autovaluo y  plano de áreas de Declaratoria de Fábrica_x000D_
Asimismo el inmueble cuenta con derecho de superficie a favor de Hernán Arizaga Marchena, Augusto Salomón Ruiz Palomino y Rosario Abensur Rengifo_x000D_
_x000D_
_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Clientes Particulares\\Otros Clientes\\2014\\ENERO\\TasPart004-2014-11865 DAVID RUIZ Playa Misterio");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11898","11897","ZOILO JUAN SALINAS TAPIA","ZOILO JUAN SALINAS TAPIA Y RUTH DORIS DEL CARPIO FERIA DE SALINAS","BANCO DE CREDITO DEL PERU","CALLE A MORELLI Nº 348-352 (MZ D-1 LOTE Nº 21), DISTRITO DE SAN BORJA, PROVINCIA Y DEPARTAMENTO DE LIMA","08/01/2014","LIMA","LIMA","SAN BORJA","-12.0914487719472","-77.0038837533950","RDB","2","300.00","1300.00","248.00","458745.60","","2.9","El siguiente informe se realizó por exteriores y con la documentación entregada por el banco, por indicación de la funcionaria Rosa Carolina Huertas Canova Se desconoce quien hace uso del inmueble_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco. Credito\\2014\\ENERO\\TasBCP006-2014-11897 - SALINAS TAPIA ZOILO JUAN");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11873","11872","IVAN FERNANDO MAQUERA CONDORI","IVAN FERNANDO MAQUERA CONDORI","BANCO DE CREDITO DEL PERU","LOTE 29 DE LA MANZANA B, URBANIZACIÓN LOS ANGELES, SEGUNDO SECTOR DE LA UNIDAD D  DE LA URBANIZACIÓN LAS FLORES, DISTRITO DE SAN JUAN DE LURIGANCHO, PROVINCIA Y DEPARTAMENTO DE LIMA","06/01/2014","LIMA","LIMA","SAN JUAN DE LURIGANCHO","-12010456362627400","-7699493967933030","RDM","1","16758.00","500.00","924.00","1237068.00","","2.9","El siguiente informe se realizó con la documentación entregada por el banco El inmueble se encuentra siendo usado por el propietario_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_
","Y:\\OPERACIONES\\Tasaciones\\Bco Credito\\2014\\ENERO\\TasBCP004-2014-11872 - MAQUERA CONDORI IVAN FERNANDO");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11874","11873","SERVICIOS GENERALES JHAN MARCO EIRL","LUCIA DEL PILAR VILLANUEVA ORTEGA Y LUCIA ORTEGA GARCIA DE VILLANUEVA","BANCO CONTINENTAL","AV DEL SUR Nª 115-119-121 Y AV PRIMAVERA Nª 1000 Y 1012, URB CHACARILLA DEL ESTANQUE, DISTRITO DE SANTIAGO DE SURCO, PROVINCIA Y DEPARTAMENTO DE LIMA","02/01/2014","LIMA","LIMA","SANTIAGO DE SURCO","-12110426496793700","-7697584579121700","RDM","1","9886.00","3000.00","55879.00","3172000.00","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral Nº44485842 y Autovalúo 2,013 ","Y:\\OPERACIONES\\Tasaciones\\Bco Continental\\2014\\ENERO\\TasBBVA001-2014-11873 - SERVCIOS GENERALES JAHN MARCO");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11879","11878","MOP PERU TRADING SAC","MEMORACION ORTIS DOROTEO Y BLANCA NIEVE VILLARRUEL DE ORTIZ","BANCO CONTINENTAL","AV LOS INGENIEROS Nª 369, LTE 25 DE LA MZ O, URBANIZACION SANTA RAQUEL  PRIMERA ETAPA ZONA ESTE, DISTRITO DE LA MOLINA, PROVINCIA Y DEPARTAMENTO DE LIMA","02/01/2014","LIMA","LIMA","LA MOLINA","-12063861599342300","-7695053045812760","RDM","4","160.00","1400.00","4487.00","320000.00","","2.8","Para la elaboración del presente informe se contó con la información proporcionada por el Banco: Partida Registral Nº 45288595 y Autovalúo del año 2013  Durante la inspección ocular se nos informó que por ordenanza de la Municipalidad de la Molina el cuarto piso no podrá ser concluido","Y:\\OPERACIONES\\Tasaciones\\Bco Continental\\2014\\ENERO\\TasBBVA002-2014-11878 -  MOP PERU TRADING SAC");
INSERT INTO t_imput_casa(proyecto_id,informe_id,cliente,propietario,solicitante,ubicacion,tasacion_fecha,ubi_departamento,ubi_provincia,ubi_distrito,mapa_latitud,mapa_longitud,zonificacion,piso_cantidad,terreno_area,terreno_valorunitario,edificacion_area,valor_comercial,areas_complementarias,tipo_cambio,observacion,ruta_informe) VALUES ("11876","11875","TURISMO DIVINO SEÑOR SAC","CILA ANCCASI CHUCHÓN Y HEBER ANCCASI CHUCHÓN","BANCO DE CREDITO DEL PERU","JIRÓN BERLÍN, CUARTA CUADRA, ASOCIACIÓN DE VIVIENDA CASCADAS DE JAVIER PRADO, MANZANA R, LOTE 24, DISTRITO DE ATE, PROVINCIA Y DEPARTAMENTO DE LIMA","02/01/2014","LIMA","LIMA","ATE VITARTE","-12039888233232300","-7692887147994000","RDM","2","160.00","450.00","2968.00","11420496.00","","2.9","El siguiente informe se realizó con las partidas de la vivienda, entregadas por el banco No se tiene conocimiento sobre la ocupación del inmueble, debido a que la tasación se realizó por exteriores, según las indicaciones de la funcionaria Rosa Carolina Huertas Canova_x000D_
_x000D_
El inmueble no se encuentra ubicado dentro de la zona considerada como Patrimonio Cultural de la Humanidad_x000D_
_x000D_
Asimismo el valor final alcanzado contempla las cargas, gravámenes y características que sobre este pesan_x000D_","Y:\\OPERACIONES\\Tasaciones\\Bco Credito\\2014\\ENERO\\TasBCP003-2014-11875 - TURISMO DIVINO SEÑOR EIRL");
