DROP TABLE IF EXISTS ubi_distrito;
CREATE TABLE ubi_distrito(
         distrito_id BIGINT
       , provincia_id BIGINT
       , nombre VARCHAR(500)
       , PRIMARY KEY (distrito_id)
)CHARACTER SET utf8;-- , ENGINE=InnoDB;

INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('1', '1', 'EL MUYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('2', '1', 'COPALLIN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('3', '1', 'CHIRIACO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('4', '1', 'BAGUA CHICA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('5', '2', 'CHURUJA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('6', '2', 'POMACHOCAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('7', '2', 'JAZAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('8', '2', 'JUNBILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('9', '3', 'CHACHAPOYAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('10', '3', 'CHUQUIBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('11', '3', 'LA JALCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('12', '3', 'LEIMEBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('13', '3', 'DURAZNOPAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('14', '3', 'MOLINO PAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('15', '4', 'CENEPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('16', '4', 'SANTA MARIA DE NIEVA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('17', '5', 'COLLONCE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('18', '5', 'CAMPORREDONDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('19', '5', 'COCABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('20', '5', 'COLCAMAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('21', '5', 'LAMUD');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('22', '5', 'LUYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('23', '5', 'OCALLI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('24', '5', 'SANTO TOMAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('25', '5', 'TINGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('26', '6', 'HUAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('27', '6', 'LIMABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('28', '6', 'LONCAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('29', '6', 'OMIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('30', '6', 'SANTA ROSA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('31', '6', 'SAN NICOLAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('32', '7', 'BAGUA GRANDE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('33', '7', 'CAJARUCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('34', '7', 'CUMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('35', '7', 'JAMALCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('36', '7', 'LONYA GRANDE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('37', '7', 'CAJARUCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('38', '7', 'CAMPORREDONDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('39', '7', 'OMIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('40', '7', 'LA JALCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('41', '7', 'SAN NICOLAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('42', '8', 'LLAMELLIN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('43', '9', 'CHIQUIAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('44', '10', 'ANTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('45', '10', 'CARHUAZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('46', '10', 'MARCARÁ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('47', '11', 'CASMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('48', '11', 'CASMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('49', '11', 'YAUTAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('50', '12', 'CORONGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('51', '13', 'TACLLAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('52', '13', 'SAN GERONIMO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('53', '13', 'HUARAZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('54', '13', 'MONTERREY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('55', '14', 'HUARI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('56', '15', 'HUARMEY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('70', '20', 'SAN JACINTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('71', '20', 'BUENOS AIRES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('72', '20', 'MACATE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('73', '20', 'MORO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('74', '20', 'SAMANCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('75', '20', 'ALTO PERU');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('76', '20', 'SANTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('77', '21', 'SIHUAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('78', '22', 'MANCOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('79', '22', 'YUNGAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('80', '22', 'YANAMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('81', '23', 'LAMBRANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('82', '23', 'ABANCAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('83', '23', 'CACHORRA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('84', '23', 'CARUHUASI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('85', '23', 'HUANIPACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('86', '24', 'HUANCARAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('87', '24', 'ANDARACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('88', '24', 'CHICMO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('89', '24', 'PACUCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('90', '24', 'SAN JERONIMO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('91', '24', 'PAMPACHIRI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('92', '24', 'ANDAHUAYLAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('93', '24', 'SAN ANTONIO DE CACHI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('94', '24', 'HUANCARAMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('95', '24', 'TALAVERA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('96', '25', 'PACHACONAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('97', '26', 'CHALHUANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('98', '26', 'COTARUSE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('99', '27', 'URIPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('100', '27', 'HUACCANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('101', '27', 'OCOBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('102', '27', 'URANMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('103', '27', 'CHINCHEROS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('104', '27', 'COTABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('105', '28', 'MAMARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('106', '28', 'CHUQUIBAMBILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('107', '29', 'ALTO SELVA ALEGRE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('108', '29', 'INDEPENDENCIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('109', '29', 'SANTA MARTHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('110', '29', 'PALACIO VIEJO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('111', '29', 'ACEQUIA ALTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('112', '29', 'CAYMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('113', '29', 'CASIMIRO CUADROS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('114', '29', 'CIUDAD MUNICIPAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('115', '29', 'CERRO COLORADO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('116', '29', 'RAMON CASTILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('117', '29', 'CHARACATO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('118', '29', 'HUNTER');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('119', '29', 'JOSE LUIS BUSTAMANTE Y RIVERO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('120', '29', 'SIMON BOLIVAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('121', '29', 'LA JOYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('122', '29', 'MARIANO MELGAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('123', '23', 'ALTO MISTI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('124', '29', 'MIRAFLORES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('125', '29', 'JUAN DE DIOS - COLCA APAZA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('126', '29', 'CIUDAD BLANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('127', '29', 'SABANDIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('128', '29', 'SACHACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('129', '29', 'PAMPA DE CAMARONES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('130', '29', 'SANTA RITA DE SIHUAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('131', '29', 'SANTA RITA DE SIHUAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('132', '29', 'CIUDAD MI TRABAJO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('133', '29', 'SOCABAYA PUEBLO TRADICIONAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('134', '29', 'TIABAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('135', '29', 'CONGATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('136', '29', 'UCHUMAYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('137', '29', 'YANAHUARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('138', '29', 'YARABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('139', '29', 'YURA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('140', '29', 'ZAMÁCOLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('141', '30', 'APLAO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('142', '30', 'PAMPACOLNA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('143', '30', 'CORIDE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('144', '30', 'VIRACO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('145', '31', 'CABANACONDE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('146', '31', 'CAYLLONA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('147', '31', 'CHIVAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('148', '31', 'HUAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('149', '31', 'EL PEDREGAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('150', '31', 'SIBAYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('151', '32', 'CHUQUIBAMBAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('152', '32', 'ARCATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('153', '32', 'ANDARAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('154', '33', 'MOLLENDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('155', '33', 'COCACHACRA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('156', '33', 'LA CURVA - DEAN VALDIVIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('157', '33', 'EL ARENAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('158', '33', 'MATARANI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('159', '33', 'MEJÍA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('160', '33', 'ISLAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('161', '33', 'PUNTA DE BOMBON');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('162', '33', 'EL ARENAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('163', '34', 'COTAHUASI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('164', '35', 'PARAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('165', '35', 'CHUSQUI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('166', '36', 'HUAMANGA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('167', '36', 'CARMEN ALTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('168', '36', 'QUINUA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('169', '36', 'VINCHOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('170', '36', 'ACOS VINCHOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('171', '37', 'HUANCA SANTOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('172', '38', 'HUANTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('173', '38', 'HUAMANGUILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('174', '39', 'SAN FRANCISCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('175', '39', 'MACHENTE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('176', '39', 'TAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('177', '39', 'SAN MIGUEL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('178', '40', 'PUQUIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('179', '40', 'AUCARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('180', '40', 'CABANA SUR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('181', '40', 'CORACORA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('182', '41', 'CANARIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('183', '41', 'HUANCAPI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('184', '42', 'QUEROBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('185', '43', 'CACHARI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('186', '43', 'CAJABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('187', '43', 'CONDEBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('188', '43', 'LLUCHUBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('189', '44', 'CAJAMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('190', '44', 'JESUS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('457', '103', 'LA MOLINA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('467', '103', 'LA VICTORIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('466', '103', 'LINCE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('465', '103', 'LOS OLIVOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('464', '103', 'MAGDALENA DEL MAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('463', '103', 'MIRAFLORES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('475', '103', 'PUEBLO LIBRE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('458', '103', 'PUENTE PIEDRA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('459', '103', 'RIMAC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('460', '103', 'SAN BORJA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('461', '103', 'SAN ISIDRO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('462', '103', 'SAN JUAN DE LURIGANCHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('476', '103', 'SAN JUAN DE MIRAFLORES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('477', '103', 'SAN LUIS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('478', '103', 'SAN MARTIN DE PORRES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('479', '103', 'SAN MIGUEL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('480', '103', 'SANTA ANITA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('481', '103', 'SANTA ROSA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('482', '103', 'SANTIAGO DE SURCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('483', '103', 'SURQUILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('484', '103', 'VILLA EL SALVADOR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('485', '103', 'VILLA MARIA DEL TRIUNFO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('486', '104', 'BARRANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('487', '104', 'PARAMONGA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('488', '104', 'PATIVILCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('489', '104', 'SUPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('490', '104', 'PUERTO SUPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('491', '105', 'CAJATAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('492', '105', 'GORGOR - HUACHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('493', '106', 'CANTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('494', '106', 'YANGAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('495', '107', 'CAÑETE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('496', '107', 'ASIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('497', '107', 'CALANGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('498', '107', 'CERRO AZUL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('499', '107', 'CHILCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('500', '107', 'IMPERIAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('501', '107', 'MALA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('502', '107', 'NUEVO IMPERIAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('503', '107', 'PUEBLO NUEVO DE CONTA ROMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('504', '107', 'QUILMANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('505', '107', 'SAN ANTONIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('506', '107', 'SAN LUIS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('507', '107', 'SAN VICENTE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('508', '107', 'LUNAHUANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('509', '108', 'CHANCAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('510', '108', 'AULLANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('511', '108', 'HUARAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('512', '108', 'SAN MIGUEL DE ACOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('513', '109', 'HUAROCHIRI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('514', '109', 'CASAPALCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('515', '109', 'RICARDO PALMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('516', '109', 'SANTA EULALIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('517', '109', 'MATUCANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('518', '109', 'SAN MATEO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('519', '109', 'SAN DAMIAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('520', '110', 'HUACHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('521', '110', 'HUAURA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('522', '110', 'CRUZ BLANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('523', '110', 'SAYAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('524', '110', 'VEGUETA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('525', '111', 'CHURIN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('526', '111', 'OYON');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('527', '112', 'CATAHUASI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('528', '112', 'YAUYOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('529', '113', 'LAGUNAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('530', '113', 'YURIMAGUAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('531', '114', 'NAUTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('532', '114', 'SANTA RITA DE CASTILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('533', '114', 'TIGRE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('534', '114', 'TROMPETEROS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('535', '114', 'URARINAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('536', '114', 'SAN REGIS SILVA MERINO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('537', '115', 'PEBAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('538', '115', 'CABALLO COCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('539', '115', 'SAN PABLO DE LORETO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('540', '116', 'SANTA MARIA DE NANAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('541', '116', '9 DE OCTUBRE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('542', '116', 'BELEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('543', '116', 'FERNANDO LORES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('544', '116', 'INDIANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('545', '116', 'MORONA COCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('546', '116', 'IQUITOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('547', '116', 'MAZAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('548', '116', 'SANTA CLOTILDE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('549', '116', 'PUNCHANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('550', '116', 'EL ESTRECHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('551', '116', '9 DE OCTUBRE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('552', '116', 'BELEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('553', '116', 'FERNANDO LORES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('554', '116', 'INDIANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('555', '116', 'MORONA COCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('556', '116', 'IQUITOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('557', '116', 'MAZAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('558', '116', 'SANTA CLOTILDE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('559', '116', 'PUNCHANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('560', '116', 'EL ESTRECHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('561', '117', 'REQUENA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('562', '118', 'CONTAMANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('563', '119', 'HUEPETUCHE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('564', '120', 'SAN LORENZO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('565', '120', 'IÑAPARI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('566', '120', 'IBERIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('567', '121', 'LABERINTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('568', '121', 'TAMBOPATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('569', '121', 'PUERTO MALDONADO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('570', '122', 'CHOJATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('571', '122', 'QUINISTAQUILLAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('572', '123', 'ILO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('573', '123', 'DEL PUERTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('574', '123', 'PAMPA INALAMBRICA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('575', '123', 'CIUDAD NUEVA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('576', '124', 'CARUMAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('577', '124', 'MOQUEGUA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('578', '124', 'SAMEGUA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('579', '124', 'CALACOA - BELLAVISTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('580', '124', 'CIUDAD NUEVO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('581', '124', 'CARUMAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('582', '125', 'SANTA ANA DE TUSI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('583', '125', 'YANAHUANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('584', '126', 'OXAPAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('585', '126', 'POZUZO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('586', '126', 'PUERTO BERMUDEZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('587', '126', 'VILLA RICA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('588', '127', 'HUACHON');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('589', '127', 'HUARIACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('590', '127', 'PAUCARTAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('591', '127', 'MILPO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('592', '127', 'COLQUIJIRCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('593', '127', 'YANACANCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('594', '127', 'CHICRIN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('595', '128', 'AYABACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('596', '128', 'FRIAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('597', '128', 'SAN JORGE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('598', '128', 'PACAIPAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('599', '129', 'HUANCABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('600', '129', 'SAPALACHE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('601', '129', 'HUARMACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('602', '129', 'SONDOR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('603', '129', 'SONDORILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('604', '130', 'CHULUCANAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('605', '130', 'BUENOS AIRES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('606', '130', 'CHALACO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('607', '130', 'PACCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('608', '130', 'YAPATERA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('609', '130', 'LA MATANZA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('610', '130', 'MORROPON');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('611', '130', 'PALTASHACO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('612', '130', 'SANTO DOMINGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('613', '131', 'AMOTAPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('614', '131', 'CIUDAD DEL PESCADOR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('615', '131', 'PAITA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('616', '131', 'LA HUACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('617', '131', 'PUEBLO NUEVO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('618', '132', 'PIURA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('619', '132', 'TACALA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('620', '132', 'EL INDIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('621', '132', 'CASTILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('622', '132', 'LA LEGUA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('623', '132', 'CATACAOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('624', '132', 'CUCUNGARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('625', '132', 'LA ARENA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('626', '132', 'LA UNION');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('627', '133', 'BERNAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('628', '133', 'PARACHIQUE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('629', '133', 'PUERTO RICO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('630', '133', 'SECHURA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('631', '134', 'PEDRO GALVEZ GALINDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('632', '134', 'BELLAVISTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('633', '134', 'SAN JACINTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('634', '134', 'MARCAVELICA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('635', '134', 'QUERECOTILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('636', '134', 'SALITRAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('637', '134', 'SULLANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('638', '134', 'LOMAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('639', '135', 'LOS ORGANOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('640', '135', 'MANCORA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('641', '135', 'NEGRITOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('642', '135', 'TALARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('643', '136', 'ARAPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('644', '136', 'ASILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('645', '136', 'AZANGARO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('646', '136', 'CHOQUEHUANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('647', '136', 'SAN ANTON');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('648', '137', 'CRUCERO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('649', '137', 'MACUSANI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('650', '137', 'DESAGUADERO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('651', '137', 'JULI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('652', '137', 'KELLUPO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('653', '137', 'POMATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('654', '137', 'ZEPITA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('655', '138', 'ILAVE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('656', '138', 'MAZO DE CRUZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('657', '139', 'COJATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('658', '139', 'HUANCANE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('659', '139', 'PUSI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('660', '139', 'ROSASPATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('661', '140', 'AYAVIRI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('662', '140', 'NUNOA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('663', '140', 'ORURILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('664', '140', 'SANTA ROSA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('665', '141', 'NINATAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('666', '141', 'CONIMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('667', '141', 'MOHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('668', '142', 'PUNO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('669', '143', 'PUTINA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('670', '143', 'ANANEA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('671', '144', 'JULIACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('672', '144', 'CABANILLAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('673', '144', 'CARACOTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('674', '144', 'SANTA BARBARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('675', '145', 'HUANCANE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('676', '146', 'LIMBANI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('677', '146', 'SAN JUAN DE ORO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('678', '146', 'SANDIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('679', '147', 'ANAPIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('680', '147', 'UNICACHI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('681', '147', 'YUNGUYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('682', '148', 'BELLAVISTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('683', '149', 'SAN JOSE DE SISA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('684', '150', 'SACANCHE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('685', '150', 'SAPOSOA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('686', '151', 'CAYNARACHI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('687', '151', 'LAMAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('688', '151', 'TABALOSOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('689', '152', 'MARISCAL CACERES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('690', '152', 'JUANJUL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('691', '153', 'JEPELACIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('692', '153', 'UCHUGLLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('693', '153', 'MOYOBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('694', '153', 'SORITOR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('695', '154', 'PICOTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('696', '155', 'PARDO MIGUEL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('697', '155', 'NUEVA CAJAMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('698', '155', 'RIOJA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('699', '155', 'YURACYACU');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('700', '156', 'CHAZUTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('701', '156', 'LA BANDA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('702', '156', 'MORALES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('703', '156', 'TARAPOTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('704', '157', 'NUEVO PROGRESO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('705', '157', 'TOCACHE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('706', '157', 'UCHIZA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('707', '158', 'CAIRANI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('708', '158', 'CANDARAVE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('709', '158', 'CURIBAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('710', '159', 'TOQUEPALA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('711', '159', 'ILABAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('712', '160', 'ALTO DE LA ALIANZA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('713', '160', 'CALANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('714', '160', 'CIUDAD NUEVA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('715', '160', 'PACHIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('716', '160', 'POCOLLAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('717', '160', 'SAMA LAS YARAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('718', '160', 'GREGORIO ABARRACIN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('719', '160', 'LA NATIVIDAD');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('720', '160', 'VIGIL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('721', '161', 'ESTIQUE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('722', '162', 'ZORRITOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('723', '162', 'CANCAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('724', '163', 'CORRALES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('725', '163', 'LA CRUZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('726', '163', 'PAMPAS DE HOSPITAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('727', '163', 'SAN JACINTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('728', '163', 'SAN JUAN DE LA VIRGEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('729', '163', 'PUERTO PIZARRO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('730', '163', 'EL TABLAZO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('731', '163', 'ANDRES ARAUJO MORAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('732', '163', 'SAN JOSE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('733', '163', 'SAN JACINTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('734', '164', 'AGUAS VERDES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('735', '164', 'ZARUMILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('736', '165', 'ATALAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('737', '166', 'SAN FERNANDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('738', '166', 'PUCALLPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('739', '166', 'YARINACOCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('740', '167', 'AGUAYTIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('741', '103', 'ATE VITARTE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('742', '103', 'CALLAO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('743', '168', 'NO ESPECIFICO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('744', '103', 'CERCADO DE LIMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('745', '103', 'BARRANCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('746', '103', 'BREÑA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('747', '103', 'COMAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('748', '103', 'CHORRILLOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('749', '103', 'EL AGUSTINO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('750', '103', 'JESUS MARIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('751', '103', 'INDEPENDENCIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('752', '103', 'ANCON');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('753', '103', 'CARABAYLLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('754', '103', 'CHACLACAYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('755', '103', 'PACHACAMAC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('756', '103', 'PUCUSANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('757', '103', 'PUNTA HERMOSA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('758', '103', 'PUNTA NEGRA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('759', '103', 'SAN BARTOLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('760', '103', 'SANTA MARIA DEL MAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('761', '55', 'CALLAO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('762', '55', 'BELLAVISTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('763', '55', 'CARMEN DE LA LEGUA REYNOSO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('764', '55', 'LA PERLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('765', '55', 'LA PUNTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('766', '55', 'VENTANILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('767', '169', 'CAMANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('191', '44', 'BAOS DEL INCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('192', '44', 'MATARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('193', '44', 'NAMORA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('194', '45', 'CHUMUCH');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('195', '45', 'HUASMIN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('196', '45', 'MIGUEL IGLESIAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('197', '45', 'OXAMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('198', '45', 'SOROCHUCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('199', '45', 'SUCRE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('200', '46', 'ANGUIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('201', '46', 'CHALAMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('202', '46', 'CHIGUIRIP');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('203', '46', 'CHIMBAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('204', '46', 'CHOTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('205', '46', 'COCHABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('206', '46', 'CONCHAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('207', '46', 'HUAMBOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('208', '46', 'LAJAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('209', '46', 'PACCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('210', '46', 'QUEROTOCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('211', '46', 'TACABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('212', '47', 'CHILETE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('213', '47', 'CONTUMAZA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('214', '47', 'CUPISMIQUE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('215', '47', 'GUZMANGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('216', '47', 'SAN BENITO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('217', '47', 'SANTA CRUZ DE TOLEDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('218', '48', 'LA CAPILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('219', '48', 'CALLAYUC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('220', '48', 'CHOROS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('221', '48', 'CUTERVO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('222', '48', 'LA RAMADA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('223', '48', 'QUEROCOTILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('224', '48', 'SAN ANDRES DE CUTERVO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('225', '48', 'SANTA CRUZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('226', '48', 'SANTO TOMÁS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('227', '48', 'SOCOTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('228', '49', 'BAMBAMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('229', '49', 'CHUGUR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('230', '49', 'HUALGAYOC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('231', '50', 'JAEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('232', '50', 'CHONTALI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('233', '50', 'COLASAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('234', '50', 'HUABAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('235', '50', 'LAS PIRIAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('236', '50', 'POMAHUACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('237', '50', 'PUCARÁ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('238', '50', 'SALLIQUE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('239', '50', 'SAN FELIPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('240', '51', 'CHIRINOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('241', '51', 'HUARANGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('242', '51', 'NAMBALLE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('243', '51', 'SAN IGNACIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('244', '51', 'SAN JOSE DE LOURDES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('245', '52', 'VENECIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('246', '52', 'ICHOCAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('247', '52', 'SAN MARCOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('248', '53', 'SAN PABLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('251', '55', 'CALLAO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('252', '55', 'RAMON CASTILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('253', '55', 'SARITA COLONIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('254', '55', 'CIUDADELA CHALACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('255', '55', 'BOCANEGRA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('256', '55', 'LA LEGUA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('257', '55', 'DULANTO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('258', '55', 'PLAYA RIMAC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('259', '55', 'JUAN INGUNZA VALDIVIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('260', '55', 'FUNDO MARQUEZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('261', '55', 'BELLAVISTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('262', '55', 'CARMEN DE LA LEGUA - REYNOSO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('263', '55', 'LA PERLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('264', '55', 'LA PUNTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('265', '55', 'MI PERU');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('266', '55', 'VENTANILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('267', '56', 'ACOMAYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('268', '56', 'ACOPÍ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('269', '56', 'MOSOC LLACTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('270', '56', 'POMACANCHI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('271', '57', 'CACHIMAYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('272', '57', 'ANTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('273', '57', 'HUAROCONGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('274', '57', 'LIMATAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('275', '57', 'MOLLEPATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('276', '57', 'PUCYURA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('277', '57', 'ZURITE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('278', '58', 'CALCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('279', '58', 'AMPARAES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('280', '58', 'PISAQ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('281', '58', 'YANATILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('282', '59', 'LANGUI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('283', '59', 'YANATILA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('284', '60', 'CANCHIS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('285', '60', 'CHECACUPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('286', '60', 'COMBAPATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('287', '60', 'MARANGANI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('288', '60', 'PITUMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('289', '60', 'SICUANI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('290', '60', 'TINTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('291', '61', 'VELILLE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('292', '61', 'SANTO TOMAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('293', '62', 'SIPASPUCYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('294', '62', 'TAHUANTISUYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('295', '62', 'CUZCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('296', '62', 'POROY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('297', '62', 'SAN JERÓNIMO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('298', '62', 'SAN SEBASTIÁN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('299', '62', 'SANTIAGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('300', '62', 'VIVA EL PERÚ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('301', '62', 'ZARZUELA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('302', '62', 'SAYLLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('303', '62', 'WANCHAQ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('304', '63', 'YAURI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('305', '64', 'LA CONVENCIÓN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('306', '64', 'QUILLABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('307', '65', 'CAMANTI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('308', '65', 'ANDAHUAYLAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('309', '65', 'PAUCARTAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('310', '65', 'PILCOPATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('311', '65', 'QUIQUIJANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('312', '65', 'URCOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('313', '66', 'MACHUPICCHU');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('314', '66', 'OLLANTAYTAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('315', '66', 'URUBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('316', '66', 'CHINCHEROS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('317', '67', 'ACOBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('318', '67', 'PUCARÁ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('319', '68', 'CCOCHACCASA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('320', '68', 'CONGALLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('321', '68', 'LIRCAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('322', '69', 'HUACHOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('323', '69', 'CASTROVIRREYNA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('324', '69', 'TANTARÁ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('325', '69', 'TIPACRO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('326', '70', 'CHURCAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('327', '70', 'SAN MIGUEL DE MAYOC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('328', '71', 'HUANCAVELICA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('329', '71', 'MOYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('330', '71', 'ACORIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('331', '71', 'HUACHOCOLPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('332', '71', 'YAULI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('333', '72', 'HUAYTARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('334', '72', 'SANTIAGO DE CHOCORVOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('335', '72', 'CÓRDOVA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('336', '73', 'HUANDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('337', '73', 'PAMPAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('338', '74', 'AMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('339', '75', 'HUAYCABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('340', '76', 'LLATA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('341', '77', 'AMARILIS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('342', '77', 'HUANUCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('343', '77', 'CAYHUAYNA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('344', '77', 'ACOMAYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('345', '77', 'HUÁNUCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('346', '78', 'JESÚS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('347', '78', 'BAÑOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('348', '79', 'TINGO MARÍA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('349', '79', 'CAYUMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('350', '79', 'AUCAYACU');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('351', '79', 'PANAO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('352', '79', 'CHAVINILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('353', '80', 'CHINCHA BAJA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('354', '80', 'CHINCHA ALTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('355', '80', 'EL CARMEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('356', '80', 'GROCIO PRADO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('357', '80', 'PUEBLO NUEVO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('358', '80', 'SUNAMPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('359', '81', 'ICA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('360', '81', 'TINGUIÑA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('361', '81', 'OCUCAJE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('362', '81', 'PARCONA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('363', '81', 'SALAS DE GUADALUPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('364', '81', 'SAN JOSÉDE LOS MOLINOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('365', '81', 'SAN JUAN BAUTISTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('366', '81', 'SANTIAGO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('367', '81', 'SUBTANJALLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('368', '82', 'NAZCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('369', '82', 'MARCONA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('370', '83', 'PALPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('371', '84', 'PISCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('372', '84', 'PARACAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('373', '84', 'SAN ANDRÉS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('374', '84', 'SAN CLEMENTE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('375', '84', 'PARACAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('376', '84', 'TUPAC AMARU');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('377', '85', 'LA MERCED');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('378', '85', 'PERENÉ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('379', '85', 'PICHANAKI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('380', '85', 'SAN RAMÓN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('381', '86', 'CHUPACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('382', '87', 'CONCEPCIÓN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('383', '88', 'CHILCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('384', '88', 'EL TAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('385', '88', 'HUAYUCACHI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('386', '88', 'SAN AGUSTÍn DE CAJAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('387', '88', 'SAN JERÓMIMO DE TUNAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('388', '88', 'SAPALLANGA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('389', '88', 'SICAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('390', '89', 'ACOYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('391', '89', 'JAUJA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('392', '90', 'JUNÍN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('393', '91', 'MAZAMARRI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('394', '91', 'SAN MARTIN DE PANGOA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('395', '91', 'RIO NEGRO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('396', '91', 'SATIPO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('397', '92', 'ACOBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('398', '92', 'TARMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('399', '93', 'LA OROYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('400', '93', 'MOROCOCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('401', '94', 'ASCOPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('402', '94', 'CASAGRANDE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('403', '94', 'ROMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('404', '94', 'CHICLIN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('405', '94', 'SAUSAL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('406', '94', 'CHICAMA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('407', '94', 'CHOCOPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('408', '94', 'PAIJÁN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('409', '94', 'RÁZURI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('410', '94', 'CARTAVIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('411', '94', 'SANTIAGO DE CAO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('412', '95', 'TALAMBO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('413', '95', 'CHEPEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('414', '95', 'PACANGA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('415', '95', 'PUEBLO NUEVO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('416', '95', 'CHEPEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('417', '96', 'AGALLPAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('418', '96', 'OTUZCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('419', '96', 'SALPO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('420', '96', 'SINSICAP');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('421', '96', 'USQUIL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('422', '97', 'PACASMAYO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('423', '97', 'HUAMACHUCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('424', '97', 'GUADALUPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('425', '97', 'CIUDAD DE DIOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('426', '97', 'SAL JOSÉ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('427', '97', 'SAN PEDRO DE LLOC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('428', '98', 'HUAMACHUCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('429', '99', 'NICOLÁS ALCAZAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('430', '99', 'SANCHEZ CARRIÓN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('431', '99', 'FLORENCIA DE MORA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('432', '99', 'HUANCHACO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('433', '99', 'JERUSALEN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('434', '99', 'BELLAVISTA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('435', '99', 'LAREDO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('436', '99', 'MOCHE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('437', '99', 'AYACUCHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('438', '99', 'LA NORIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('439', '99', 'CIUDAD DE DIOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('440', '99', 'CARTAVIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('441', '99', 'SALAVERRY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('442', '99', 'MIRAMAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('443', '99', 'BUENOS AIRES');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('444', '100', 'VIRÚ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('445', '101', 'FERREÑAFE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('446', '102', 'ILLIMO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('447', '102', 'JAYANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('448', '102', 'LAMBAYEQUE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('449', '102', 'MOCHUMI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('450', '102', 'CRUZ DEL MEDANO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('451', '102', 'MOTUPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('452', '102', 'OLMOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('453', '102', 'TUCUME');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('454', '102', 'POSOPE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('768', '99', 'TRUJILLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('769', '44', 'ASUNCION');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('770', '44', 'CHETILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('771', '44', 'COSPAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('772', '44', 'LLACANORA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('773', '44', 'LA ENCAÑADA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('774', '44', 'SAN JUAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('775', '44', 'MAGDALENA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('776', '103', 'ASIA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('777', '23', 'CIRCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('778', '23', 'CHACOCHE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('779', '23', 'PICHIRHUA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('780', '23', 'TAMBURCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('781', '25', 'ANTABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('782', '25', 'EL ORO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('783', '25', 'HUAQUIRCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('784', '25', 'JUAN ESPINOZA MEDRANO (Mollebamba)');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('785', '25', 'OROPESA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('786', '25', 'SABAINO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('787', '26', 'CAPAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('788', '26', 'CARAYBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('789', '26', 'CHAPIMARCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('790', '26', 'COLCABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('791', '26', 'HUAYLLO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('792', '26', 'JUSTO APU SAHUARAURA (Pichihua)');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('793', '26', 'LUCRE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('794', '26', 'POCOHUANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('795', '26', 'SAN JUAN DE CHACNA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('796', '26', 'SANAYCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('797', '26', 'SORAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('798', '26', 'TAPAIRIHUA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('799', '26', 'TINTAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('800', '26', 'TORAYA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('801', '26', 'YONACA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('802', '170', 'TAMBOBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('803', '170', 'COTABAMBAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('804', '170', 'COYLLURQUI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('805', '170', 'HAQUIRA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('806', '170', 'MARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('807', '170', 'CHALLHUAHUACHO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('808', '28', 'CURPAHUASI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('809', '28', 'GAMARRA (Palpacachi)');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('810', '28', 'HUAYLLATI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('811', '28', 'MICAELA BASTIDAS (Ayrihuanca)');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('812', '28', 'PATAYPAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('813', '28', 'PROGRESO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('814', '28', 'SAN ANTONIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('815', '28', 'SANTA ROSA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('816', '28', 'TURPAY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('817', '28', 'VILCABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('818', '28', 'VIRUNDO (San Juan de Virundo)');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('819', '28', 'CURASCO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('820', '27', 'COCHARCAS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('821', '27', 'ONGOY');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('822', '27', 'RANRACANCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('823', '24', 'CHIARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('824', '24', 'HUAYANA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('825', '24', 'KISHUARA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('826', '24', 'PACOBAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('827', '24', 'POMACOCHA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('828', '24', 'SAN MIGUEL DE CHACCRAMPA (Chaccrampa)');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('829', '24', 'SANTA MARIA DE CHICMO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('830', '24', 'TUMAY HUARACA (Umamarca)');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('831', '24', 'TURPO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('832', '24', 'KAQUIABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('249', '54', 'SANTA CRUZ');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('250', '54', 'ANDABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('833', '54', 'CATACHE');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('834', '54', 'CHANCAYBANOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('835', '54', 'LA ESPERANZA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('836', '54', 'NINABAMBA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('837', '54', 'PULAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('838', '54', 'SAUCEPAMPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('839', '54', 'SEXI');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('840', '54', 'UTICYACU');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('841', '54', 'YAUYUCAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('842', '171', 'SAN MIGUEL');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('843', '171', 'BOLIVAR');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('844', '171', 'CALQUIS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('845', '171', 'CATILLUC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('846', '171', 'EL PRADO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('847', '171', 'LA FLORIDA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('848', '171', 'LLAPA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('849', '171', 'NANCHOC');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('850', '171', 'NIEPOS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('851', '171', 'SAN GREGORIO');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('852', '171', 'SAN SILVESTRE DE CONCHAN');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('853', '171', 'TONGOD');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('854', '171', 'UNION AGUA BLANCA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('855', '172', 'OTROS');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('856', '103', 'LURIGANCHO-CHOSICA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('857', '103', 'Lurin');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('858', '103', 'CIENEGUILLA');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('859', '0', 'prueba');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('860', '0', 'prueba2');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('861', '0', 'prueba');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('862', '169', 'disttiyo de prueba');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('863', '103', 'prueba123');
INSERT INTO ubi_distrito(distrito_id, provincia_id, nombre) VALUES('864', '103', 'allemant');
    
