INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Maquina borbadora computarizada');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TOMOGRAFO HELICOIDAL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('RECTILINEA ELECTRÓNICA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CALANDRA DE TRES RODILLOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('IMPRESORA OFFSET DIGITAL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('GUILLOTINA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('IMPRESORA FLEXOGRAFICA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('BALANZA DE PLATAFORMA O BAJO PERFIL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('4');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA EXTRUSORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CONTENEDOR REFRIGERADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA CIRCULAR');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EXTRUSORA AMASADORA FAJA DE TRANSPORTE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPO DE RESONANCIA MAGNETICA.');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CAMARA DE REFRIGERACION INDUSTRIAL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPOS DE REFRIGERACIÓN PARA CÁMARAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPO PARA TÚNEL DE REFRIGERACIÓN');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPO DE PRE-ENFRIAMIENTO ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA DESHIDRATADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CONDENSADOR DEL TUNEL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TUNER DE LIOFILIZACION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('2');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('GENERADOR');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA DE CORTE Y SOLDADO ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA EXTRUSORA DE SORBETES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CARDADORA PARA ACABADOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA INYECTORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PORTABOBINA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EMPALMADOR');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TUNEL DE LIOFILIZADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA PARA TEÑIR MARCA DMS ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Centro de Mecanizado Vertical CNC');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PLATAFORMA DE TRABAJO AEREA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('RAMA PLANA KRANTZ K30 DE 6 CAMPOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('SECADORA Y TERMOFIJADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('6');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('IND ALIMENTARIA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('LINEA DE PRODUCCION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('REMOLCADOR TRACTO CAMION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('0');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('7');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('SISTEMA AUTOMATICO DE LAVADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINARIA TEXTIL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ALMACENES Y DEPOSITOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINARIA INDUSTRIA PESQUERA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CABEZALES DE BORDADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TEJEDORAS CIRCULARES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA ESTAMPADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA DISPENSADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRANSMISORES RADIALES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('GRUPO ELECTROGENO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINAS DE SOLDAR, OTROS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MUEBLES Y ENSERES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINAS DE TEJIDO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MUEBLES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ACABADO EN MADERA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('5');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CAMION Y GRUA TEL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Curtiembre de pieles');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Equipos de imprenta');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('maquinaria textl');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('1');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Equipos pc');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('maquinaria telas');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Compresora Industrial');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Equipos de baja ESSALUD');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Maquina perforadora');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Maquinarias textiles');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINAS IMPRESORAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINARIA PARA MOLDEO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Máquina inyectora para calzado');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPOS Y HERRAMIENTAS DE TALLER');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('maquina inyectora bicolor');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('3');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Bobinas de Hojalata');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Celda Robotica integral');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Balanza de plataforma de peaje');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('maquinaria y equipos');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Exacavadora y chancadora');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Maquina continua procesadora de hilo');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Maquinas continuas de hilar');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Maquina textil ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Locomotoras a vapor ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Maquina por inyeccion y un chiller ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Planta procesadora dealimentos');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('maquinas de carpinteria');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('equipos de computo ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('equipos de computo - 16 servidores ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('racks');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRENSA ENFARDADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Elevador de Rescate');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('LINEAS DE INYECCIÓN');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('LINEA DE SOPLADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CONCILIACION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRENDA GLOBAL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MEZCLADORA DE PRODUCTOS VETERINARIOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPOS VARIOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINARIAS DE PLANTA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('LINEAS DE SOPLADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('INVENTARIO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('centro de torneado');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Montacargas');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('VARIOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PERFORADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CAMION HINO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('BOBINAS GALVANIZADAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CENTRO DE MECANIZADO CNC ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ELEVADOR HIDRAULICO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('INVENTARIO DE EQUIPOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRENDA GLOBAL LLANTAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('telares');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('IMPRESORAS DE GRAN FORMATO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRODUCTOS AGROPECUARIOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('maquina de imprenta');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINARIA DE PLANTA Y VEHICULOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PLANTA MOVIL TRITURADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINAS DE TREFILADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA PARA FABRICACION DE CUADERNOS ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MARTILLO HIDRAULICO-TRASPALETA-APILADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MARTILLO HIDRAULICO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('APILADOR');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRASPALETA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('7 MÁQUINAS INYECTORAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('vehiculo');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ENRASADORA DE RECUBRIMIENTO OSCILANTE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ESPARCIDORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EXTENDEDORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('BARNIZADORAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('BARNIZADORA SECTORIZADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('barnizadora total');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TREFILADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('BALANZA PARA CAMIONES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('HORNO DE SECADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EXTRUSORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('VIBROCOMPACTADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PLANTA COMPLETA DE BLOQUE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PLANTA DE BLOQUES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MONTACARGA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRENSA HORIZONTAL');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MUEBLES, ENSERES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MONITOR');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('SILLA ALTA GIRATORIA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('SILLA BAJA RODANTE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('LECTOR CODIGO DE BARRAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MODULO DE CAJA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CPU I3 4GB RAM');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINAS CONSTRUCCION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MINICARGADOR');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('COMPRESORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MARTILLO NEUMATICO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('IMPRESORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Servidor Rack integrado ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('LIBRERIA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('STORAGE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('CAJA DE DISCOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINAS METALMECANICA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PERFORADORA AUTOMATIZADA CNC');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA METALMECANICA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MEZCLADORA DE CHOCOLATE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA PARA CHOCOLATE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('REFINADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('VALVULA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA IMPRESORA FLEXOGRÁFICA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA IMPRESORA FLEXOGRAFICA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINA PLEGADORA O DOBLADORA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRENDA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('Inventario y Conciliación');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('BOOSTER COMPRESOR ST63TBM-01 SIST. CAR');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRANSFORMADORES ELECTRICOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRANSFORMADOR TRIFASICO MARCA ABB DE 5');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRANSFORMADOR TRIFASICO MARCA ABB DE 3');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRANSFORMADOR TRIFASICO MARCA ABB DE 2');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRANSFORMADOR TRIFASICO 75 KVA  USADO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('SILLAS DE OFICINA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('VARIADA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('REACTOR R1 DE ACERO ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('VARIOS-CHATARRA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MUEB.ENS.EQUIP.COMPUTO VEHICULS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ARCHIVADOR CON 4 GAVETAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('IMPRESORA MATRICIAL  ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ECRAN RETRACTIL ELECTRICO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PEDESTAL PARA MICROFONO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PIZARRA DIGITAL ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PROYECTOR DIGITAL ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('8');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPOS DE CONSTRUCCION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRODUCTOS EMPAQUES');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('HORNO MINERO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('EQUIPOS DE LABORATORIO Y VEHICULOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ESPECTROFOTOMETRO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('HORNO PARA LABORATORIO ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINARIA DE PRODUCCION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MAQUINARIA DE PRODCUCCION');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('maquina pulidora');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PULIDORA DE PAVIMENTO');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PERFORADORA Y TRACTOR ORUGA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TRACTOR ORUGA');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('ACTIVOS FIJOS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('PRENDA DE BOBINAS');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MUEBLES, EQUIPOS DIVERSOS, EQUIPOS DE ');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('TANQUE');
INSERT INTO em_maquinaria_tipo(clasificacion) VALUES('MINERALES DE ALEACION');
    