INSERT INTO em_maquinaria_marca(nombre) VALUES('');
INSERT INTO em_maquinaria_marca(nombre) VALUES('AISLACORP');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Hyster');
INSERT INTO em_maquinaria_marca(nombre) VALUES('3M');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Allen Enginerine');
INSERT INTO em_maquinaria_marca(nombre) VALUES('APIN');
INSERT INTO em_maquinaria_marca(nombre) VALUES('APIN INGENIEROS');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Axion');
INSERT INTO em_maquinaria_marca(nombre) VALUES('BIELOMATIK');
INSERT INTO em_maquinaria_marca(nombre) VALUES('BMB');
INSERT INTO em_maquinaria_marca(nombre) VALUES('BOBCAT');
INSERT INTO em_maquinaria_marca(nombre) VALUES('BUHLER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CARLE MONTARI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CARRIER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CATERPILLAR');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CATERPILLAR/KAMA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CHICAGO PNEUMATICS');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CHICAGO PNEUMATICS - CROW');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CIOLA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CLARK');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CMS-MIEHLE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('COLUMBIA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('COMERIO ERCOLE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Compagnucci');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CONCA CARLE MONTANARI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('CROWN');
INSERT INTO em_maquinaria_marca(nombre) VALUES('DAEWOO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('DEMAQ');
INSERT INTO em_maquinaria_marca(nombre) VALUES('DIVERSO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('diversos');
INSERT INTO em_maquinaria_marca(nombre) VALUES('DMS.');
INSERT INTO em_maquinaria_marca(nombre) VALUES('DORNIER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Ecoph S.A.C');
INSERT INTO em_maquinaria_marca(nombre) VALUES('EPSON');
INSERT INTO em_maquinaria_marca(nombre) VALUES('FAIRBANK');
INSERT INTO em_maquinaria_marca(nombre) VALUES('FANGTAI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('FAST & FLUID THE TINTING');
INSERT INTO em_maquinaria_marca(nombre) VALUES('FLEXOTECNICA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('four');
INSERT INTO em_maquinaria_marca(nombre) VALUES('GEKA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('GENERAL ELECTRIC');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Ger Loto Electronica SRL');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Goodrich');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HAITIAN');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HANS BINDER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HARRIS');
INSERT INTO em_maquinaria_marca(nombre) VALUES('hass');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HBM');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HEIDELBERG');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HENKE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HIDRAULICA MOVIL (ALO LIF');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HINO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HP');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HTC');
INSERT INTO em_maquinaria_marca(nombre) VALUES('HYUNDAI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('IBIRAMA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('IMPREFLEX');
INSERT INTO em_maquinaria_marca(nombre) VALUES('INDELAR');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Jack');
INSERT INTO em_maquinaria_marca(nombre) VALUES('JEEP');
INSERT INTO em_maquinaria_marca(nombre) VALUES('JLG');
INSERT INTO em_maquinaria_marca(nombre) VALUES('JOHN DEERE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('JOHS KRAUJE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Kingkong');
INSERT INTO em_maquinaria_marca(nombre) VALUES('komatsu');
INSERT INTO em_maquinaria_marca(nombre) VALUES('LAMPERTI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('LEADWELL');
INSERT INTO em_maquinaria_marca(nombre) VALUES('LENOVO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('LIDA MACHINE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Lincoln electric');
INSERT INTO em_maquinaria_marca(nombre) VALUES('LIYU INJET PRINTER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('LORENZIN S.P.A');
INSERT INTO em_maquinaria_marca(nombre) VALUES('LUNG MENG MACHINERY & Co');
INSERT INTO em_maquinaria_marca(nombre) VALUES('M&R');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Magitech');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Manroland');
INSERT INTO em_maquinaria_marca(nombre) VALUES('MARQUIP');
INSERT INTO em_maquinaria_marca(nombre) VALUES('MARVI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('MARZOLI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('MATAN');
INSERT INTO em_maquinaria_marca(nombre) VALUES('MELCO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Memory Kings');
INSERT INTO em_maquinaria_marca(nombre) VALUES('METTLER TOLEDO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('MOENUS TEXTILMASCHIENEN G');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Moritzu');
INSERT INTO em_maquinaria_marca(nombre) VALUES('MS SOUZA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('n/d');
INSERT INTO em_maquinaria_marca(nombre) VALUES('NILPETER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('NW');
INSERT INTO em_maquinaria_marca(nombre) VALUES('OERLIKON – SAURER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('OLIVINI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('ORIZIO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('OSXP D201 SOMERO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('PAI - LUNG');
INSERT INTO em_maquinaria_marca(nombre) VALUES('PEDDINGHAUS  MDL 1000');
INSERT INTO em_maquinaria_marca(nombre) VALUES('PEDDINGHAUS - GEKA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('POLAR MOHR');
INSERT INTO em_maquinaria_marca(nombre) VALUES('POLIBLOCK');
INSERT INTO em_maquinaria_marca(nombre) VALUES('PRECISION');
INSERT INTO em_maquinaria_marca(nombre) VALUES('PROTTI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('RICOH PRO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('RIETER');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Rimoldi, Santex, FONGS, B');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Riskema');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Rizzi');
INSERT INTO em_maquinaria_marca(nombre) VALUES('RNP');
INSERT INTO em_maquinaria_marca(nombre) VALUES('RUTI');
INSERT INTO em_maquinaria_marca(nombre) VALUES('SIALF');
INSERT INTO em_maquinaria_marca(nombre) VALUES('SIDEL');
INSERT INTO em_maquinaria_marca(nombre) VALUES('SIEMENS');
INSERT INTO em_maquinaria_marca(nombre) VALUES('SIERRA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('SOMERO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('SOMERO ENTERPRISES');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Sullair');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Sun Microsystems');
INSERT INTO em_maquinaria_marca(nombre) VALUES('SYNCRO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('tajima');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TAMROCK');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TASACIÓN EN GABINETE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TCM');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TERROT');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TIEME');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TOSHIBA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TOYOTA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('TRIO EN GINEERED PRODUCT');
INSERT INTO em_maquinaria_marca(nombre) VALUES('UNIPLANET');
INSERT INTO em_maquinaria_marca(nombre) VALUES('UNITECH');
INSERT INTO em_maquinaria_marca(nombre) VALUES('UV');
INSERT INTO em_maquinaria_marca(nombre) VALUES('VAM');
INSERT INTO em_maquinaria_marca(nombre) VALUES('VARIADA');
INSERT INTO em_maquinaria_marca(nombre) VALUES('VARIADAS');
INSERT INTO em_maquinaria_marca(nombre) VALUES('vARIADO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('VARIAN');
INSERT INTO em_maquinaria_marca(nombre) VALUES('VARIOS');
INSERT INTO em_maquinaria_marca(nombre) VALUES('VOLCABLE');
INSERT INTO em_maquinaria_marca(nombre) VALUES('VOLVO');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Wagner');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Welltec- Welltec');
INSERT INTO em_maquinaria_marca(nombre) VALUES('Xerox, Ricoh, marca Sun M');
INSERT INTO em_maquinaria_marca(nombre) VALUES('ZCME');
    