INSERT INTO em_maquinaria_modelo(nombre) VALUES('');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('00462 ASSY 42305-3');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('1200SJP');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('1300/E');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('1357 EX');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('175-13');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('2-3Y/TFGN-1212');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('2256 (CON PARANTE)');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('246C');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('3020');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('305 510 2/3');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('310SG');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('320 CL Mass');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('320 DL');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('320B');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('320CL Mass');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('329D');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('3516B 1825KW PRIME');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('375 DPQ');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('380 KG-INOXIDABLE');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('420E');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('500');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('5525');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('580M');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('6000KG');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('650 HDX');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('69NT40-511');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('69NT40-511-319');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('69UG15-068S-01');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('6M');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('80 HY');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('906-CR');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('912');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('966H');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('AA220 FS');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('AA250 PL');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('AMAYA XT');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('ANGE');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('APLS160');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('AR 6000 D');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('AUDACES JET 185');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('AXERA 5 (JB003)');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Barak 5');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('BARAK 8QW');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('BARAK IQ 3 MTS');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('BL70');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('BLUSCAN');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('C39-8');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('CNC');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('CT 30X42');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('D4D - AFY1800/40/250');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('D4G');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('D6H');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('DIVERSO');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('diversos');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('DMS-11');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('DPS251');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('DUTRO 716 4TN');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Ecoph');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('ELANTRA');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('ESPARCIDORA PARA REVESTIM');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('EURO97 - 28SC');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('FAI');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('FD160S – 3EX');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('FH16');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('FRAT/T');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('FT-500-2B DOUBLE SCREW');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('FX 13;C13');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('FX-8');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('G.E.L. 86');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('GAUNTLET II');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('HA650-26');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('HDX THREE PHASE 460');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Hp Indigo press 3050');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('HRL 150');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('HTVS 4/S');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('I3');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('IF-60ADV,IV');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('IS630AN');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('J789D');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('JKY');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('K30/KM16');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Kings');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('L5000');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('LA-T-2SA');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('LÁSER SXP');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('leybold');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('LM-AH40T');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('LO 05  double rollsatnd');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('M 43/13');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('M01701');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('MANUAR RSB-D22');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('MED=0.8*0.67*0.93');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('MPP-90A');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('MSL 400');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('MSP 415');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('MULTIBELT DRYER');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('n/d');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('NSF3');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('NW80');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('P15-90');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Pantera 900');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('PATRIOT');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('pc160 lc-7');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('pc160 lc-7 aeo');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('PG 3212 XLE');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('PH1010 (SIN PARANTE)');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('PT242');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('RED.EVO.4V.6K');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Rl');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('RNS83FX-FL7');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('RODANTE');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('RR5700');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('RSB 951');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('RX29');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('sbo 4/6');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SFL1300');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SIALF Complet 1.1.10');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SIGNA CONTOUR 0.5T');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SINT TR 55A');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SOMATON EMOTION 06');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SPLICER');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SPLINCER');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SSHJ1');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('ST 3.5 yd3');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('st-30');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Storedge 3500');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Storedge C4');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('STS-132');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Sunfire E6900');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('SXP-D – LASER SCREED');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('TASACIÓN EN GABINETE');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('TERCEL XL 1.3');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('TH82');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('Thinkvision');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('TM-3P');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('TTI -140F2R - TTI -380F2R');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('ULTRA 100A');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('UP – 372 MINI JACQUARD');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('UP – 472 MINI JAQCUARD');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('V-30IG');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VAM 175-13');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VARIADA');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VARIADO');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VARIADOS');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VARIOS');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VF-3, 3 EJES  (X=1MT, Y=0');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VF-3, 5 EJES');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('VM-90L-4');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('WA500-6');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('WH520');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('WP 3000');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('X56');
INSERT INTO em_maquinaria_modelo(nombre) VALUES('ZX2000MX');
    