INSERT INTO em_vehiculo_modelo(nombre) VALUES('');
INSERT INTO em_vehiculo_modelo(nombre) VALUES(' Elantra');
INSERT INTO em_vehiculo_modelo(nombre) VALUES(' FH 12,');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('1214/48');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('12546894');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('1418/48');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('15.190E');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('1500 GAL');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('154454');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('17.220');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('17.220 E3');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('1718/48');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('1725');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('17250E');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('18.310');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('18.310T');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('19.320');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('206');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('2418/48');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('3000 GAL');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('3251-2006');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('335I');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('4300 – 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('4300 SBA 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('4300 SBS 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('520 CNG 1.3 EX/2008');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('709/37');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('7400 SBA 6X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('7500 SBA 6X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('7600 – 6X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('7600 SBA 6X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('7600-SBA 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('9.150');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('914/42.5');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('9400i');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ACCENT ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ACCENT GLS');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ACCORD');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('AERIO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ALTO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ATEGO 1628/54');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('AVENGER 200');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('AVEO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('boxer');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('C200 KOMPRESOR');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('C230 KOMPRESSOR ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('C39-8');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CA5013XXYA5');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CA5013XXYA8');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CAMRY');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CAMRY 3.0');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CAMRY 3.5');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CANTER TURBO TD T5 5 TON');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CAYENNE S TIPTRONIC');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CB6X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CC170E22');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CEH-SRV-03');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CHEROKEE SPORT');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CHEVY TAXI');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CHEVY-TAXI');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CI-RF-02');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('COMPASS');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Contenedor Cilindrico');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('COROLLA');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('COROLLA GLI 1.6');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('COROLLA XLi');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('COROLLA XLI 1.6 A');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('COROLLAXLI 1.6 A/T');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CROSSFOX 1.6/2008');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CRV. ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('CX-9');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('d302');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('DFA1102GZ5AD6');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('DUTRO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('E32-501');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('e350');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('e500');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ELANTRA');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ELANTRA FL 1.6');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('ELANTRA GLS');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('EXPEDITION');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('F12');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('F400');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('FH12 6X4T ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('FIERA 4 X 2 / 2003');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('FIERA 4.2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('FO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('FRONTIER');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('GRAND CHEROKEE LIMITED');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('GRAND NOMADE');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('GRAND VITARA');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('H-1 3 VAN. ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('H-1 6 VAN');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('H-1 M/BUS. ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('H100 TRUCK');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('haval h5');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HD 120');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HD-65');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HD65');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HDG');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HFC1061K');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HFC106K');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('hg4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HI LUX');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HIGER  BUS KLQ6758');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HILUX');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HILUX 4 x 4.');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HILUX 4X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HILUX 4X4 C/D TURBO DSL');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('HILUX CD TURBO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Incapower B50');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Incapower B60');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('jy41');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('K124IB8X2NB380');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('K2700');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('K3000');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('KANGOO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('KLQ6728G');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('KLQ6758');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('KYRON AUT 2.3G 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('L200 CR 4X4 2.5 C/D TD GLS M/T ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('L200 DAKAR 4X2 DIC.');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('LEGACY');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Leon FR. 2.0 TFSI  TIP 2010');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('LLV2ABA1380200276');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('LS-1935/46');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('MAZDA 3');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('MEGANE');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('MEGANE SEDAN EXPRESSION');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('MODELO KYRON AUT 2.3G 4X2 / 2011');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('MURANO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('NAVARA');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('NAVARA 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('NAVARA 4X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('NEW FORESTER');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('NLMD21-SF');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('OF-1721/59');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('P380 B6X4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('PILOT');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Q5 2.0T FSI S TRONIC /201');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Q5 2.0T FSI S TRONIC /2011');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Q5 2.0T FSI S TRONIC /2014');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('RANGER');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('RANGER  CABINA DOBLE');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('RAV4');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('RIO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('RIO NB');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('Santa Fé');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('SERIE K, 6x2,');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('SORENTO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('SPORTAGE');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('SPORTAGE 2.0 AT');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('SPORTAGE 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('SR3PL');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TD12');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TIIDA');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TIIDA CONFORT 1.6 MT');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TIIDA DECO 1.6 MT');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TITÁN WOLKERS 18310');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TOWN & COUNTRY LX');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TRAKKER 380T42H');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TRIBECA');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TRIBECA 3.6R AWD 5AT 7A LIMITED');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TUCSON');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TUCSON 4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('TUCSON4X2');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('VARIADO');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('VARIOS');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('VIVANT');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('VM 6 X 2 R');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('WOEKER 15.180');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('worker');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('WORKER 15.180 ');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('WS70A');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('X3');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('XML6125J13CN');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('XML6925J13CN');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('YARIS');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('YARIS XLI 1,3 GSL');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('YARIS XLI 1.3');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('YARIS XLI 1.3 GSL');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('YARIS XLI 1.3 GSL.');
INSERT INTO em_vehiculo_modelo(nombre) VALUES('YARIS XLI 1.3 M/T');