INSERT INTO em_vehiculo_marca(nombre) VALUES('CHEVROLET');
INSERT INTO em_vehiculo_marca(nombre) VALUES('TOYOTA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('MERCEDES BENZ');
INSERT INTO em_vehiculo_marca(nombre) VALUES('RECRUSUL');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HYUNDAI');
INSERT INTO em_vehiculo_marca(nombre) VALUES('RENAULT');
INSERT INTO em_vehiculo_marca(nombre) VALUES('SUZUKI');
INSERT INTO em_vehiculo_marca(nombre) VALUES('MAZDA ');
INSERT INTO em_vehiculo_marca(nombre) VALUES('TOYOTA.');
INSERT INTO em_vehiculo_marca(nombre) VALUES('FORD');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HYUNDAI.');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HONDA.');
INSERT INTO em_vehiculo_marca(nombre) VALUES('IVECO');
INSERT INTO em_vehiculo_marca(nombre) VALUES('MITSUBISHI.');
INSERT INTO em_vehiculo_marca(nombre) VALUES('INTERNATIONAL');
INSERT INTO em_vehiculo_marca(nombre) VALUES('');
INSERT INTO em_vehiculo_marca(nombre) VALUES('PEUGEOT');
INSERT INTO em_vehiculo_marca(nombre) VALUES('NISSAN');
INSERT INTO em_vehiculo_marca(nombre) VALUES('VOLVO');
INSERT INTO em_vehiculo_marca(nombre) VALUES('CHRYSLER');
INSERT INTO em_vehiculo_marca(nombre) VALUES('VOLKSWAGEN');
INSERT INTO em_vehiculo_marca(nombre) VALUES('JEEP');
INSERT INTO em_vehiculo_marca(nombre) VALUES('SUSUKI');
INSERT INTO em_vehiculo_marca(nombre) VALUES('KIA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('KIA.');
INSERT INTO em_vehiculo_marca(nombre) VALUES('MITSUBISHI');
INSERT INTO em_vehiculo_marca(nombre) VALUES('SUBARU');
INSERT INTO em_vehiculo_marca(nombre) VALUES('CORENHA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('BULLON');
INSERT INTO em_vehiculo_marca(nombre) VALUES('BMW');
INSERT INTO em_vehiculo_marca(nombre) VALUES('JEEP');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HONDA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('SCANIA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('DONGFENG');
INSERT INTO em_vehiculo_marca(nombre) VALUES('LIFAN');
INSERT INTO em_vehiculo_marca(nombre) VALUES('VARIADO');
INSERT INTO em_vehiculo_marca(nombre) VALUES('PORSCHE');
INSERT INTO em_vehiculo_marca(nombre) VALUES('JG600');
INSERT INTO em_vehiculo_marca(nombre) VALUES('NISSA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('Caterpilla');
INSERT INTO em_vehiculo_marca(nombre) VALUES('Peugot');
INSERT INTO em_vehiculo_marca(nombre) VALUES('internacional');
INSERT INTO em_vehiculo_marca(nombre) VALUES('Fyco');
INSERT INTO em_vehiculo_marca(nombre) VALUES('BAJAJ');
INSERT INTO em_vehiculo_marca(nombre) VALUES('General Electric');
INSERT INTO em_vehiculo_marca(nombre) VALUES('Seat');
INSERT INTO em_vehiculo_marca(nombre) VALUES('WINCHE REMOLQUE ');
INSERT INTO em_vehiculo_marca(nombre) VALUES('CAISA ');
INSERT INTO em_vehiculo_marca(nombre) VALUES('KIA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('great wall');
INSERT INTO em_vehiculo_marca(nombre) VALUES('TOYOYA');
INSERT INTO em_vehiculo_marca(nombre) VALUES('VOLKWAGEN');
INSERT INTO em_vehiculo_marca(nombre) VALUES('audi');
INSERT INTO em_vehiculo_marca(nombre) VALUES('audio');
INSERT INTO em_vehiculo_marca(nombre) VALUES('FAW');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HIGER');
INSERT INTO em_vehiculo_marca(nombre) VALUES('SSANGYONG');
INSERT INTO em_vehiculo_marca(nombre) VALUES('JAC');
INSERT INTO em_vehiculo_marca(nombre) VALUES('BAW');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HYUANDAI');
INSERT INTO em_vehiculo_marca(nombre) VALUES('GOLDEN DRAGON');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HYUINDAY');
INSERT INTO em_vehiculo_marca(nombre) VALUES('INTERNATIONAL');
INSERT INTO em_vehiculo_marca(nombre) VALUES('B Y D');
INSERT INTO em_vehiculo_marca(nombre) VALUES('HINO');
INSERT INTO em_vehiculo_marca(nombre) VALUES('DYM');
INSERT INTO em_vehiculo_marca(nombre) VALUES('VARIOS');
INSERT INTO em_vehiculo_marca(nombre) VALUES('JEPP');
    